<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_apc_dc_metamodel_environment_loader() {
    $items[] = array(
        'classname' => 'APCEnvironmentMetaModelGenerator');

    return $items;
}

function data_controller_apc_dc_cache() {
    $items[APCHandler::$CACHE__TYPE] = array(
        'classname' => 'APCHandler');

    return $items;
}
