<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/
 

function data_uploader_get_source_metadata(AbstractUploadRequest $uploadRequest, array $dataSubmitters = NULL) {
    $parser = $uploadRequest->prepareDataParser();
    $dataProvider = $uploadRequest->prepareDataProvider();
    
    $recordCount = $parser->parse($dataProvider, $dataSubmitters);

    $uploadRequest->metadata = $parser->metadata;

    return $recordCount;
}

function data_uploader_store_source_data(AbstractUploadRequest $uploadRequest, array $dataSubmitters) {
    $parser = $uploadRequest->prepareDataParser();
    $dataProvider = $uploadRequest->prepareDataProvider();

    $recordCount = $parser->parse($dataProvider, $dataSubmitters);

    return $recordCount;
}
