<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/



/*
 * @file
 *
 * Working sample module to demonstrate CTools 3 plugins
 *
 * This sample module is only intended to demonstrate how external modules can
 * provide ctools plugins. There is no useful functionality, and it's only
 * intended for developers or for educational use.
 *
 * 
 *
 * There is a demonstration panel provided at /checkbook_panels/123
 */


/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * checkbook_panels/panels are used.
 */
function checkbook_panels_plugins_ctools_plugin_directory($module, $plugin) {

  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implement hook_ctools_plugin_api().
 *
 * If you do this, CTools will pick up default panels pages in
 * <modulename>.pages_default.inc
 */
function checkbook_panels_ctools_plugin_api($module, $api) {
  // @todo -- this example should explain how to put it in a different file.
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}



/**
 * Implementation of hook_menu.. USed for dsiplaying popups.
 * @return multitype:string boolean multitype:number
 */
function checkbook_panels_plugins_menu(){ 
  $items['minipanels/%'] = array(
      'page callback' => 'checkbook_panels_get_minipanel',
      'access callback' => true,
      'page arguments' => array(1),
      'type'=>MENU_CALLBACK
  );
  $items['panel_html/%'] = array(
      'page callback' => 'checkbook_panels_get_panel_html',
      'access callback' => true,
      'page arguments' => array(1),
      'type'=>MENU_CALLBACK
   );

  return $items;
}

function checkbook_panels_get_minipanel($panel_name){
  $panel_mini = panels_mini_load($panel_name);
  echo  panels_render_display($panel_mini->display);
}

function checkbook_panels_get_panel_html($panel_name){
  require_once(drupal_get_path('module', 'page_manager') . '/plugins/tasks/page.inc');
  $result = page_manager_page_execute($panel_name);
  if(is_array($result)){
    $output = $result['content']['#markup'];
  } else{
    $output = $result;
  }
  echo  "<div class=\"page-contract-details "  . $panel_name . "\">" .$output  . "</div>";
}


