<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
*
* Copyright (C) 2012, 2013 New York City
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

function checkbook_alerts_init(){
  require_once(drupal_get_path("module","checkbook_alerts")."/includes/checkbook_alerts.inc");
}

/**
 * Implements hook_menu().
 */
function checkbook_alerts_menu() {
  $items = array();
  $items['alert/transactions/form'] = array(
    'title' => 'Checkbook Alerts',
    'page callback' => '_checkbook_alerts_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['alert/transactions'] = array(
    'title' => 'Checkbook Alerts',
    'page callback' => '_checkbook_alerts_transactions',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'weight' => 1,
  );
  $items['alert/unsubscribe'] = array(
    'title' => 'Checkbook Alerts',
    'page callback' => '_checkbook_alerts_unsubscribe',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}


/**
 * Implements hook_theme().
 */
function checkbook_alerts_theme($existing, $type, $theme, $path) {
  return array(
    'checkbook_alerts_default_theme'=>array(
      'template'=>'checkbook_alerts',
      'arguments'=>array('maxPages'=>NULL,
                         'totalRecords'=>NULL,
                         'displayRecords'=>NULL
      )
    )
  );
}
