<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_contrib_rest_server_rest_server_response_formatters_alter(&$formatters) {
    $formatters['txt'] = array(
        'mime types' => array('text/plain'),
        'view' => 'TextResponseFormatView');
}
