<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (c) 2012 – 2023 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use Drupal\checkbook_infrastructure_layer\Utilities\FormattingUtilities;
use Drupal\checkbook_infrastructure_layer\Utilities\RequestUtilities;
use Drupal\Core\Url;

/**
 * Implements hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */

function checkbook_widget_retroactivity_theme($existing, $type, $theme, $path) {
  return [
    'retroactivity_tabs' => [
      'variables' => [
        'main_heading' => NULL,
        'sub_heading' => NULL,
        'active_tab' => NULL,
        'tabs' => [],
      ],
    ],
    'retroactivity_tab_header' => [
      'variables' => ['main_title' => NULL, 'sub_title' => NULL],
    ],
    'retroactivity_chart_tiles' => [
      'variables' => ['tiles' => []],
    ],
    'retroactivity_chart_placeholder' => [
      'variables' => [
        'chart_id' => NULL,
      ],
    ],
  ];
}