<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/*************************************************************************************/
/* Widget Hooks                                                                      */
/*************************************************************************************/

function widget_wt_widget_metadata() {
	return array(
    'wt' => array(
      'name' => t('Widget Widget Table'),
      'module' => 'widget_wt',
      'description' => t("This widget type implements a table that can output other widgets.")
	)
	);
}

function widget_wt_widget_validate(&$node) {

}

function widget_wt_widget_data(&$node) {

}


function widget_wt_widget_view(&$node) {
	if (!isset($node->data) || count($node->data) == 0) {
		return theme('widget_wt_no_results_theme', array('node'=> $node));
	}
	else if (isset($node->widgetConfig->table_rows)) {
		return theme('widget_wt_by_rows_theme', array('node'=> $node));
	}
	else {
		return theme('widget_wt_default_theme', array('node'=> $node));
	}
}

/*************************************************************************************/
/* Theme Hooks                                                                       */
/*************************************************************************************/

function widget_wt_theme($existing, $type, $theme, $path) {
	return array(
      'widget_wt_default_theme' => array(
	    'template' => 'wt_table',
        'arguments' => array('node' => NULL),
	  ),
	  'widget_wt_by_rows_theme' => array(
	    'template' => 'wt_table_by_rows',
	    'arguments' => array('node' => NULL),
	  ),
	  'widget_wt_no_results_theme' => array(
	    'template' => 'wt_no_results',
	    'arguments' => array('node' => NULL),
	  ),	  
	);
}
