language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

git:
  depth: 3

before_script:
  - phpenv versions
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

script:
  - phpunit --no-logging
