<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_mysql_ddl_dc_datasource_structure() {
    $items[MySQLDataSource::TYPE] = array(
        'handler' => 'DefaultSQLDataSourceStructureHandler',
        'extensions' => array(
            'createDatabase' => 'DefaultCreateDatabaseStatementImpl',
            'dropDatabase' => 'DefaultDropDatabaseStatementImpl',

            'createTable' => 'MySQLCreateTableStatementImpl',
            'truncateTable' => 'DefaultTruncateTableStatementImpl',
            'dropTable' => 'DefaultDropTableStatementImpl'
        )
    );

    return $items;
}
