<?php

/**
 * Implements hook_menu().
 */
function checkbook_etl_notification_menu(){
  $items['etl_stats'] = array(
    'title' => 'Checkbook ETL Statistics',
    'page callback' => 'checkbook_etl_notification_mail',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function checkbook_etl_notification_mail(){
  var_dump(CheckbookEtlStatistics::gatherData($message));
}

/**
 * Implements hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function checkbook_etl_notification_theme($existing, $type, $theme, $path)
{
  if ($type == 'module') {
    return array(
      'etl_status_email' => array(
        'variables' => array(
          'uat_status' => NULL,
          'prod_status' => NULL,
        ),
        'template' => 'etl-status.email',
        'path' => drupal_get_path('module', 'checkbook_etl_notification') . '/theme',
      ),
    );
  }
}
