<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/




function data_controller_metamodel_drupal_content_type_dc_metamodel_loader() {
    $items[] = array(
        'classname' => 'DrupalContentTypeMetaModelLoader');

    return $items;
}

function data_controller_metamodel_drupal_content_type_dc_dataset_assembler() {
    $items[ContentTypeDatasetSourceAssembler::$DATASET_SOURCE_ASSEMBLER__TYPE] = array(
        'classname' => 'ContentTypeDatasetSourceAssembler');

    return $items;
}
