<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (C) 2012, 2013 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


function checkbook_solr_menu()
{
  $items['solr_options'] = array(
    'title' => '',
    'page callback' => 'checkbook_solr_options',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * @param string $data_source
 * @param string $domain
 * @param string $facet
 */
function checkbook_solr_options(string $data_source, string $domain, string $facet)
{
  $Guru = CheckbookGuruOptionsJson::get_instance($data_source);
  $Guru->setFq('domain',"domain:{$domain}");
  $facets = drupal_get_query_parameters();
  $is_autocomplete = FALSE;

  foreach($facets as $fq => $value){
    if ('term' == $fq) {
      if ($value) {
        $Guru->setFqAutocompleteTerm($facet, $value);
      }
      $is_autocomplete = TRUE;
      continue;
    }
    $Guru->setFq($fq,"{$fq}:{$value}");
  }
  $data = $Guru->get_all($facet);
  if ($is_autocomplete) {
    if (!$data) {
      $data = [['label' => 'No Matches Found', 'value' => '']];
    } else {
      foreach ($data as &$line) {
        $line['value'] = urlencode($line['value']);
      }
    }
  }
  drupal_json_output($data);
  return;
}
