<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/




function data_controller_datasource_sql_dc_log_message_listener() {
    $items[] = array(
        'classname' => 'StatementLogMessageKeeper',
        'priority' => -1000);
    $items[] = array(
        'classname' => 'StatementLogMessageFormatter',
        'priority' => -10); // has to be greater than of TextLogMessageTrimmer to avoid possible SQL text truncation in log

    return $items;
}
