<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (c) 2012 – 2023 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use Drupal\data_controller_postgresql\PostgreSQLDataSource;

function data_controller_postgresql_dc_datasource() {
    $items[PostgreSQLDataSource::TYPE] = array(
        'extensions' => array(
            'getMaximumEntityNameLength' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLMaximumEntityNameLengthImpl',

            'concatenateValues' => '\Drupal\data_controller_postgresql\Handler\DefaultConcatenateValuesImpl',
            'formatWildcardValue' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLFormatWildcardValueImpl',
            'formatDateValue' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLFormatDateValueImpl',
            'formatRegularExpression' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLRegularExpressionValueImpl',
            'formatNotRegularExpression' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLNotRegularExpressionValueImpl',

            'initializeConnection' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLInitializeConnectionImpl',
            'executeStatement' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\PDOExecuteStatementImpl',
            'executeQueryStatement' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\PDOExecuteQueryStatementImpl',
            'executeQueryStatement_callback' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLQueryStatementExecutionCallback',

            'startTransaction' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\DefaultStartTransactionStatementImpl',
            'commitTransaction' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\DefaultCommitTransactionStatementImpl',
            'rollbackTransaction' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\DefaultRollbackTransactionStatementImpl',

            'getDataSourceOwner' => '\Drupal\data_controller_postgresql\Handler\PostgreSQLDataSourceOwnerImpl'
        )
    );

    return $items;
}

function data_controller_postgresql_dc_datasource_query() {
    $items[PostgreSQLDataSource::TYPE] = array(
        'handler' => '\Drupal\data_controller_sql\Datasource\Handler\DefaultSQLDataSourceQueryHandler',
        'extensions' => array(
            'isJoinSupported' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\DefaultCheckJoinSupportImpl',
            'applyPagination' => '\Drupal\data_controller_sql\Datasource\Handler\Impl\DefaultImpl\DefaultApplyPaginationImpl'
        )
    );

    return $items;
}
