<?php

function checkbook_etl_status_enable() {
  $current = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  $addition = array('mymodule' => 'CheckbookMailSystem');
  variable_set('mail_system', array_merge($current, $addition));
}

function checkbook_etl_status_disable() {
  $mail_system = variable_get('mail_system', array('default-system' => 'DefaultMailSystem'));
  unset($mail_system['mymodule']);
  variable_set('mail_system', $mail_system);
}
