<?php

include_once 'includes/CheckbookEtlStatus.class.php';

/**
 * Implements hook_cron()
 */
function checkbook_etl_status_cron()
{
  $CES = new CheckbookEtlStatus();
  return $CES->run_cron();
}

/**
 * Implements hook_mail().
 *
 * @param $key
 * @param $message
 * @param $params
 */
function checkbook_etl_status_mail($key, &$message, $params)
{
  $CES = new CheckbookEtlStatus();
  $CES->mail($message);
}

/**
 * Implements hook_mail_alter().
 *
 * Adds priority headers to messages passing condition.
 */
function checkbook_etl_status_mail_alter(&$message) {
  if (stripos($message['subject'], 'Fail')) {
    $message['headers']['X-Priority'] = '1 (Highest)';
    $message['headers']['X-MSMail-Priority'] = 'High';
    $message['headers']['Importance'] = 'High';
  }
  $message['headers']['Content-Type'] = 'text/html; charset="UTF-8"';
  $replace_from = [
    "\tSuccess",
    "\tFail"
  ];
  $replace_to = [
    "\t<em>Success</em>",
    "\t<strong>Fail</strong>",
  ];
  $message['body'] = str_replace('\tSuccess','<strong>Success</strong>', $message['body']);

}
