<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/





/** Implementation of hook block view alter
 * @param $data
 * @param $block
 */
function checkbook_trends_block_view_alter(&$data, $block){
  if(preg_match('/trends/',$block->delta )){
    foreach($data['content'] as $key=>$item){
      if(isset($item['#href'])) $data['content'][$key]['#href'] = 'trends-landing/' . $item['#href'] ;
    }
  }
}

/**
 * Implementation of hook_theme() ...
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array   
 */
function checkbook_trends_theme($existing, $type, $theme, $path){
    $node = 'undefined';
    return array(
        'trends_general_fund_revenue_other_fin_sources' => array(
            'template' => 'templates/financial_trends/general_fund_revenue_other_fin_sources',
            'arguments' => array('node' => $node)
        ),
        'trends_general_fund_revenue_other_fin_sources_csv' => array(
            'template' => 'templates/financial_trends/general_fund_revenue_other_fin_sources_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_general_fund_expend_other_fin_sources' => array(
            'template' => 'templates/financial_trends/general_fund_expend_other_fin_sources',
            'arguments' => array('node' => $node)
        ),
        'trends_general_fund_expend_other_fin_sources_csv' => array(
            'template' => 'templates/financial_trends/general_fund_expend_other_fin_sources_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_fund_bal_govt_funds' => array(
            'template' => 'templates/financial_trends/fund_bal_govt_funds',
            'arguments' => array('node' => $node)
        ),
        'trends_fund_bal_govt_funds_csv' => array(
            'template' => 'templates/financial_trends/fund_bal_govt_funds_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_changes_in_fund_bal' => array(
            'template' => 'templates/financial_trends/changes_in_fund_bal',
            'arguments' => array('node' => $node)
        ),
        'trends_changes_in_fund_bal_csv' => array(
            'template' => 'templates/financial_trends/changes_in_fund_bal_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_changes_in_net_assets' => array(
            'template' => 'templates/financial_trends/changes_in_net_assets',
            'arguments' => array('node' => $node)
        ),
        'trends_changes_in_net_assets_csv' => array(
            'template' => 'templates/financial_trends/changes_in_net_assets_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_capital_proj_rev_by_agency' => array(
            'template' => 'templates/financial_trends/capital_proj_rev_by_agency',
            'arguments' => array('node' => $node)
        ),
        'trends_capital_proj_rev_by_agency_csv' => array(
            'template' => 'templates/financial_trends/capital_proj_rev_by_agency_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_nyc_edu_const_fund' => array(
            'template' => 'templates/financial_trends/nyc_edu_const_fund',
            'arguments' => array('node' => $node)
        ),
        'trends_nyc_edu_const_fund_csv' => array(
            'template' => 'templates/financial_trends/nyc_edu_const_fund_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_nyc_population' => array(
            'template' => 'templates/demographic_trends/nyc_population',
            'arguments' => array('node' => $node)
        ),
        'trends_nyc_population_csv' => array(
            'template' => 'templates/demographic_trends/nyc_population_csv',
            'arguments' => array('node' => $node)
        ),
    	'trends_personal_income_tax_revenues' => array(
            'template' => 'templates/demographic_trends/personal_income_tax_revenues',
            'arguments' => array('node' => $node)
        ),
        'trends_personal_income_tax_revenues_csv' => array(
            'template' => 'templates/demographic_trends/personal_income_tax_revenues_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_non_agr_employment' => array(
            'template' => 'templates/demographic_trends/non_agr_employment',
            'arguments' => array('node' => $node)
        ),
        'trends_non_agr_employment_csv' => array(
            'template' => 'templates/demographic_trends/non_agr_employment_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_persons_rec_pub_asst' => array(
            'template' => 'templates/demographic_trends/persons_rec_pub_asst',
            'arguments' => array('node' => $node)
        ),
        'trends_persons_rec_pub_asst_csv' => array(
            'template' => 'templates/demographic_trends/persons_rec_pub_asst_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_emp_status_of_resident_population' => array(
            'template' => 'templates/demographic_trends/emp_status_of_resident_population',
            'arguments' => array('node' => $node)
        ),
        'trends_emp_status_of_resident_population_csv' => array(
            'template' => 'templates/demographic_trends/emp_status_of_resident_population_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_assesed_val_and_estd_act_val' => array(
            'template' => 'templates/revenue_capacity_trends/assesed_val_and_estd_act_val',
            'arguments' => array('node' => $node)
        ),
        'trends_assesed_val_and_estd_act_val_csv' => array(
            'template' => 'templates/revenue_capacity_trends/assesed_val_and_estd_act_val_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_tax_rate_by_class' => array(
            'template' => 'templates/revenue_capacity_trends/assessed_val_and_tax_rate_by_class',
            'arguments' => array('node' => $node)
        ),
        'trends_tax_rate_by_class_csv' => array(
            'template' => 'templates/revenue_capacity_trends/assessed_val_and_tax_rate_by_class_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_property_tax_rates' => array(
            'template' => 'templates/revenue_capacity_trends/property_tax_rates',
            'arguments' => array('node' => $node)
        ),
        'trends_property_tax_rates_csv' => array(
            'template' => 'templates/revenue_capacity_trends/property_tax_rates_csv',
            'arguments' => array('node' => $node)
        ),
	    'trends_property_tax_levies' => array(
            'template' => 'templates/revenue_capacity_trends/property_tax_levies',
            'arguments' => array('node' => $node)
	    ),
        'trends_property_tax_levies_csv' => array(
            'template' => 'templates/revenue_capacity_trends/property_tax_levies_csv',
            'arguments' => array('node' => $node)
    	),
        'trends_collections_cancellations_abatements' => array(
            'template' => 'templates/revenue_capacity_trends/collections_cancellations_abatements',
            'arguments' => array('node' => $node)
        ),
        'trends_collections_cancellations_abatements_csv' => array(
            'template' => 'templates/revenue_capacity_trends/collections_cancellations_abatements_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_uncollected_parking_violation_fee' => array(
            'template' => 'templates/revenue_capacity_trends/uncollected_parking_violation_fee',
            'arguments' => array('node' => $node)
        ),
        'trends_uncollected_parking_violation_fee_csv' => array(
            'template' => 'templates/revenue_capacity_trends/uncollected_parking_violation_fee_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_hudson_yards_infra_corp' => array(
            'template' => 'templates/revenue_capacity_trends/hudson_yards_infra_corp',
            'arguments' => array('node' => $node)
        ),
        'trends_hudson_yards_infra_corp_csv' => array(
            'template' => 'templates/revenue_capacity_trends/hudson_yards_infra_corp_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_cap_assets_stats_by_program' => array(
            'template' => 'templates/operational_trends/cap_assets_stats_by_program',
            'arguments' => array('node' => $node)
        ),
        'trends_cap_assets_stats_by_program_csv' => array(
            'template' => 'templates/operational_trends/cap_assets_stats_by_program_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_no_of_city_employees' => array(
            'template' => 'templates/operational_trends/no_of_city_employees',
            'arguments' => array('node' => $node)
        ),
        'trends_no_of_city_employees_csv' => array(
            'template' => 'templates/operational_trends/no_of_city_employees_csv',
            'arguments' => array('node' => $node)
        ),
    	'trends_ratios_of_outstanding_debt' => array(
            'template' => 'templates/debt_capacity_trends/ratios_of_outstanding_debt',
            'arguments' => array('node' => $node)
    	),
        'trends_ratios_of_outstanding_debt_csv' => array(
            'template' => 'templates/debt_capacity_trends/ratios_of_outstanding_debt_csv',
            'arguments' => array('node' => $node)
    	),
        'trends_ratios_of_general_bonded_debt' => array(
            'template' => 'templates/debt_capacity_trends/ratios_of_general_bonded_debt',
            'arguments' => array('node' => $node)
        ),
        'trends_ratios_of_general_bonded_debt_csv' => array(
            'template' => 'templates/debt_capacity_trends/ratios_of_general_bonded_debt_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_pledged_revenue_coverage_nyc' => array(
            'template' => 'templates/debt_capacity_trends/pledged_revenue_coverage_nyc',
            'arguments' => array('node' => $node)
        ),
        'trends_pledged_revenue_coverage_nyc_csv' => array(
            'template' => 'templates/debt_capacity_trends/pledged_revenue_coverage_nyc_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_legal_debt_margin' => array(
            'template' => 'templates/debt_capacity_trends/legal_debt_margin',
            'arguments' => array('node' => $node)
        ),
        'trends_legal_debt_margin_csv' => array(
            'template' => 'templates/debt_capacity_trends/legal_debt_margin_csv',
            'arguments' => array('node' => $node)
        ),
        'trends_pledged_rev_cov_nyc_trans' => array(
            'template' => 'templates/debt_capacity_trends/pledged_rev_cov_nyc_trans',
            'arguments' => array('node' => $node)
        ),
        'trends_pledged_rev_cov_nyc_trans_csv' => array(
            'template' => 'templates/debt_capacity_trends/pledged_rev_cov_nyc_trans_csv',
            'arguments' => array('node' => $node)
        )
    
    );
}


function checkbook_trends_alter_data_tables_columns($node){
	$columns = array();
	$columns[] = array('label'=>'category'); 
	foreach( $node->data as $row){
			$columns[] = array('label'=>'fiscal_year') ;
	}
	
}


function checkbook_trends_menu(){

	$items['export/download/trends_property_tax_levies_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_property_tax_levies_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_ratios_of_outstanding_debt_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_ratios_of_outstanding_debt_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_personal_income_tax_revenues_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_personal_income_tax_revenues_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_emp_status_of_resident_population_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_emp_status_of_resident_population_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_collections_cancellations_abatements_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_collections_cancellations_abatements_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_nyc_edu_const_fund_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_nyc_edu_const_fund_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_nyc_population_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_nyc_population_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_persons_rec_pub_asst_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_persons_rec_pub_asst_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_assesed_val_and_estd_act_val_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_assesed_val_and_estd_act_val_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_property_tax_rates_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_property_tax_rates_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_tax_rate_by_class_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_tax_rate_by_class_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_hudson_yards_infra_corp_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_hudson_yards_infra_corp_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_ratios_of_general_bonded_debt_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_ratios_of_general_bonded_debt_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_pledged_revenue_coverage_nyc_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_pledged_revenue_coverage_nyc_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_general_fund_revenue_other_fin_sources_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_general_fund_revenue_other_fin_sources_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_general_fund_expend_other_fin_sources_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_general_fund_expend_other_fin_sources_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_fund_bal_govt_funds_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_fund_bal_govt_funds_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_changes_in_fund_bal_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_changes_in_fund_bal_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_changes_in_net_assets_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_changes_in_net_assets_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_capital_proj_rev_by_agency_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_capital_proj_rev_by_agency_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_non_agr_employment_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_non_agr_employment_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_uncollected_parking_violation_fee_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_uncollected_parking_violation_fee_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_cap_assets_stats_by_program_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_cap_assets_stats_by_program_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_no_of_city_employees_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_no_of_city_employees_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
    $items['export/download/trends_legal_debt_margin_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_legal_debt_margin_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	$items['export/download/trends_pledged_rev_cov_nyc_trans_csv'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_trends_default_download',
		'page arguments' => array(4,"trends_pledged_rev_cov_nyc_trans_csv"),
	    'access callback' => true,
        'type' => MENU_CALLBACK,
	);
	return $items;
}


function _checkbook_trends_default_download($node,$template = null){
	$_GET['q'] = check_plain($_GET['dataUrl']);
	
	$nodeId = RequestUtilities::get('node');
	
	$node = node_load($nodeId);
    widget_config($node);
    //prepare anything we'll need before loading
    widget_prepare($node);
    //invoke widget specific prepare
    //widget_invoke($node, 'widget_prepare');
    
    //TODO - see if we have to check count again
    $node->widgetConfig->getTotalDataCount = false;
    $node->widgetConfig->getData = true;
    //load data
    widget_data($node);

	drupal_add_http_header("Content-Type", "text/csv");
	drupal_add_http_header("Content-Disposition", "attachment; filename=\"" . str_replace(' ', '_',$node->body['und'][0]['summary']) . ".csv\"");
	drupal_add_http_header("Pragma", "cache");
	drupal_add_http_header("Expires", "-1");
	if(isset($template))
		echo theme($template,array('node' => $node));
	else
		echo theme("trends_default_csv",array('node' => $node));
} 



