<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/




function views_fusioncharts_multipleseries_init() {
    drupal_add_js(drupal_get_path('module', 'views_fusioncharts_multipleseries') .'/fusioncharts/FusionCharts.js');
}

/**
 * Implementation of hook_views_api().
 */
function views_fusioncharts_multipleseries_views_api() {
    return array('api' => 3);
}

/**
 * Implementation of hook_views_plugin().
 */
function views_fusioncharts_multipleseries_views_plugins() {
    $path = drupal_get_path('module', 'views_fusioncharts_multipleseries');
    $theme_path = "$path/theme";
    $config = array(
        'module'  => 'views_fusioncharts_multipleseries',
        'style'   => array( // Declare this style plugin.
            'views_fusioncharts_multipleseries' => array(
                'title'           => 'FusionCharts (Multiple-Series)',
                'path'            => $path,
                'help'            => 'Displays views as multiple-series FusionCharts',
                'handler'         => 'views_plugin_style_fusioncharts_multipleseries',
                'theme'           => 'views_views_fusioncharts_multipleseries_style',
                'theme path'      => $theme_path,
                'uses row plugin' => FALSE,
                'uses fields'     => TRUE,
                'uses options'    => TRUE,
                'type'            => 'normal',
                'even empty'      => FALSE
            )
        )
    );
    //kpr($config); die();
    return $config;
}

//this is a theme pre-process function where we can prepare variables for the template
function template_preprocess_views_views_fusioncharts_multipleseries_style(&$vars) {
    global $base_path;

    $options = $vars['options'];
    $view = $vars['view'];
    $rows_in = $vars['rows'];
    $fields = &$view->field;

    $config = new DOMDocument;
    $chart = $config->createElement('chart');
    $config->appendChild($chart);

    $hasStyle = FALSE;
    $styles = $config->createElement('styles');
    $definition = $config->createElement('definition');
    $application = $config->createElement('application');
    $styles->appendChild($definition);
    $styles->appendChild($application);

    // Captioning
    if (drupal_strlen(trim($options['chart_title'])) > 0) {
        $chart->setAttribute('caption', trim($options['chart_title']));
    }
    if (drupal_strlen(trim($options['chart_subtitle'])) > 0) {
        $chart->setAttribute('subcaption', trim($options['chart_subtitle']));
    }
    // Axes
    if (drupal_strlen(trim($options['xaxisname'])) > 0) {
        $chart->setAttribute('xaxisname', trim($options['xaxisname']));
    }
    if (drupal_strlen(trim($options['yaxisname'])) > 0) {
        $chart->setAttribute('yaxisname', trim($options['yaxisname']));
    }
    if (drupal_strlen(trim($options['yaxismax'])) > 0 && floatval($options['yaxismax']) != 00) {
        $chart->setAttribute('yAxisMaxValue', floatval($options['yaxismax']));
    }

    // Formatting of displayed numeric values
    if (isset($options['values']['show'])) {
        $chart->setAttribute('showValues', intval($options['values']['show']));
    }
    if (isset($options['values']['rotate'])) {
        $chart->setAttribute('rotateValues', intval($options['values']['rotate']));
    }
    if (isset($options['values']['inside'])) {
        $chart->setAttribute('placeValuesInside', intval($options['values']['inside']));
    }

    // General number formatting
    if (isset($options['numformat']['commas']) && intval($options['numformat']['commas']) >= 0) {
        $chart->setAttribute('formatNumber', intval($options['numformat']['commas']));
    }
    if (isset($options['numformat']['abbreviate']) && intval($options['numformat']['abbreviate']) >= 0) {
        $chart->setAttribute('formatNumberScale', intval($options['numformat']['abbreviate']));
    }
    if (isset($options['numformat']['decimals']) && intval($options['numformat']['decimals']) >= 0) {
        $chart->setAttribute('decimals', intval($options['numformat']['decimals']));
    }
    if (isset($options['numformat']['prefix']) && drupal_strlen($options['numformat']['prefix']) > 0) {
        $chart->setAttribute('numberPrefix', trim($options['numformat']['prefix']));
    }
    if (isset($options['numformat']['suffix']) && drupal_strlen($options['numformat']['suffix']) > 0) {
        $chart->setAttribute('numberSuffix', trim($options['numformat']['suffix']));
    }

    // Formatting of column/bar elements
    if (isset($options['column']['shadow'])) {
        $chart->setAttribute('showColumnShadow', intval($options['column']['shadow']));
    }
    if (isset($options['column']['rotate'])) {
        $chart->setAttribute('rotateNames', intval($options['column']['rotate']));
    }

    // Formatting of tooltips
    if (isset($options['tooltips']['bgcolor']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['tooltips']['bgcolor'])) {
        $chart->setAttribute('toolTipBgColor', ltrim(drupal_strtoupper($options['tooltips']['bgcolor']), '#'));
    }
    if (isset($options['tooltips']['border']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['tooltips']['border'])) {
        $chart->setAttribute('toolTipBorderColor', ltrim(drupal_strtoupper($options['tooltips']['border']), '#'));
    }

    // General appearance formatting
    if (isset($options['appearance']['border'])) {
        $chart->setAttribute('showBorder', intval($options['appearance']['border']));
    }
    $bgTop = ltrim(drupal_strtoupper($options['appearance']['bg_top']), '#');
    $bgBottom = ltrim(drupal_strtoupper($options['appearance']['bg_bottom']), '#');
    if (!preg_match('!^[0-9A-F]{6}$!', $bgTop)) {
        $bgTop = 'FFFFFF';
    }
    if (!preg_match('!^[0-9A-F]{6}$!', $bgBottom)) {
        $bgBottom = 'FFFFFF';
    }
    $chart->setAttribute('bgColor', "$bgBottom,$bgTop");

    $alphaTop = intval($options['appearance']['alpha_top']);
    $alphaBottom = intval($options['appearance']['alpha_top']);
    $alphaTop = min(100, max(0, $alphaTop));
    $alphaBottom = min(100, max(0, $alphaBottom));
    $chart->setAttribute('bgAlpha', "$alphaBottom,$alphaTop");
    $rounded = FALSE;

    if (isset($options['appearance']['round'])) {
        $rounded = intval($options['appearance']['round']);
        $chart->setAttribute('useRoundEdges', $rounded);
    }
    if (!$rounded && isset($options['appearance']['border_thickness'])) {
        $chart->setAttribute('plotBorderThickness', intval($options['appearance']['border_thickness']));
    }
    if (isset($options['appearance']['showalternate'])) {
        if (strpos($options['chart_type'], 'Bar') !== FALSE) {
            $attribName = 'showAlternateVGridColor';
        }
        else {
            $attribName = 'showAlternateHGridColor';
        }
        $chart->setAttribute($attribName, intval($options['appearance']['showalternate']));
    }
    if (isset($options['appearance']['animation'])) {
        $chart->setAttribute('animation', intval($options['appearance']['animation']));
    }
    if (isset($options['appearance']['bordercolor'])  && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['appearance']['bordercolor'])) {
        $chart->setAttribute('plotBorderColor', ltrim(drupal_strtoupper($options['appearance']['bordercolor']), '#'));
    }

    $chart->setAttribute('plotgradient', '!' . $options['appearance']['plotgradient'] . '!');

    $chart->setAttribute('plotFillRatio', isset($options['appearance']['plotgradient']) && $options['appearance']['plotgradient'] ? '0' : '100');

    // Fonts
    if (isset($options['fonts']['basefamily']) && drupal_strlen(trim($options['fonts']['basefamily'])) > 0) {
        $chart->setAttribute('baseFont', trim($options['fonts']['basefamily']));
    }
    if (isset($options['fonts']['basesize']) && intval($options['fonts']['basesize']) > 0) {
        $chart->setAttribute('baseFontSize', floatval($options['fonts']['basesize']));
    }
    $fontobjects = array('caption', 'datalabels', 'subcaption', 'xaxisname', 'xaxisvalues', 'yaxisname', 'yaxisvalues');
    foreach ($fontobjects as $fontobject) {
        if (views_fusioncharts_add_style($options, $fontobject, $definition, $application)) {
            $hasStyle = TRUE;
        }
    }

    // Dividing lines configuration
    if (isset($options['divlines']['number']) && intval($options['divlines']['number']) > 0) {
        $chart->setAttribute('numDivLines', intval($options['divlines']['number']));
        if (isset($options['divlines']['color']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['divlines']['color'])) {
            $chart->setAttribute('divLineColor', ltrim(drupal_strtoupper($options['divlines']['color']), '#'));
        }
        if (isset($options['divlines']['dashed']) && $options['divlines']['dashed']) {
            $chart->setAttribute('divLineIsDashed', '1');
            if (isset($options['divlines']['dashlen']) && intval($options['divlines']['dashlen']) > 0) {
                $chart->setAttribute('divLineDashLen', intval($options['divlines']['dashlen']));
            }
            if (isset($options['divlines']['dashgap']) && intval($options['divlines']['dashgap']) > 0) {
                $chart->setAttribute('divLineDashGap', intval($options['divlines']['dashgap']));
            }
        }
    }

    // Data fields
    $xfield = views_fusioncharts_get_field_alias($options['xaxisfield'], $fields);
    $seriesConfig = array();
    for($i = 0; $i < 6; $i++) {
        $thisOpt = $options['series' . $i];
        if (!isset($thisOpt) || empty($thisOpt['yaxisfield']) || empty($thisOpt['label'])) {
            continue;
        }
        $series = array();
        $series['yaxisfield'] = views_fusioncharts_get_field_alias($thisOpt['yaxisfield'], $fields);
        $series['label'] = $thisOpt['label'];
        if (isset($thisOpt['color']) && preg_match('!^#?[0-9A-F]{6}$!i', $thisOpt['color'])) {
            $series['color'] = ltrim(drupal_strtoupper($thisOpt['color']), '#');
        }

        if (isset($thisOpt['linkfield']) && ($linkfield = views_fusioncharts_get_field_alias($thisOpt['linkfield'], $fields))) {
            $series['linkfield'] = $linkfield;
        }
        if (isset($thisOpt['tooltipfield']) && ($tooltipfield = views_fusioncharts_get_field_alias($thisOpt['tooltipfield'], $fields))) {
            $series['tooltipfield'] = $tooltipfield;
        }
        $seriesConfig[] = $series;
    }

    $hasHTMLTooltext = FALSE;
    $categories = array();
    $datasets = array();

    $i = 0;
    foreach ($rows_in as $row) {
        $i++;
        $row = views_fusioncharts_views_render_fields($view, $row);
        if (!isset($row->$xfield)) {
            continue;
        }
        $categories[] = $row->$xfield;

        foreach ($seriesConfig as $series) {
            $label = $series['label'];
            if (!isset($datasets[$label])) {
                $datasets[$label] = array();
            }
            $dataset = array();
            $yaxisfield = $series['yaxisfield'];
            $dataset['value'] = $row->$yaxisfield;
            if (isset($series['color'])) {
                $dataset['color'] = $series['color'];
            }
            if (isset($series['linkfield'])) {
                $linkfield = $series['linkfield'];
                if (isset($row->$linkfield)) {
                    $dataset['link'] = trim(str_replace('&amp;', '&', $row->$linkfield));
                }
            }
            if (isset($series['tooltipfield'])) {
                $tooltextField = $series['tooltipfield'];
                if (isset($row->$tooltextField)) {
                    $tooltext = $row->$tooltextField;
                    if (!$hasHTMLTooltext && $tooltext != strip_tags($tooltext)) {
                        $hasHTMLTooltext = TRUE;
                    }
                    $dataset['toolText'] = str_replace("\r\n", "\n", $tooltext);
                }
            }
            $datasets[$label][] = $dataset;
        }
    }

    $catsElement = $config->createElement('categories');
    foreach ($categories as $catLabel) {
        $catElement = $config->createElement('category');
        $catElement->setAttribute('label', $catLabel);
        $catsElement->appendChild($catElement);
    }
    $chart->appendchild($catsElement);

    foreach ($datasets as $label => $dataset) {
        $datasetElement = $config->createElement('dataset');
        $datasetElement->setAttribute('seriesName', $label);
        if (isset($dataset[0]['color'])) {
            $datasetElement->setAttribute('color', $dataset[0]['color']);
        }
        foreach ($dataset as $set) {
            $setElement = $config->createElement('set');
            foreach ($set as $key => $val) {
                if ($key != 'color') {
                    $setElement->setAttribute($key, $val);
                }
            }
            $datasetElement->appendChild($setElement);
        }
        $chart->appendChild($datasetElement);
    }

    if ($hasHTMLTooltext) {
        $hasStyle = TRUE;

        $style = $config->createElement('style');
        $style->setAttribute('name', 'tooltip_style');
        $style->setAttribute('type', 'font');
        $style->setAttribute('isHTML', '1');
        $definition->appendChild($style);

        $apply = $config->createElement('apply');
        $apply->setAttribute('toObject', 'TOOLTIP');
        $apply->setAttribute('styles', 'tooltip_style');
        $application->appendChild($apply);
    }
    if ($hasStyle) {
        $chart->appendChild($styles);
    }

    $configstring = $config->saveXML($chart);

    $vars['chartID'] = $view->name . '__' . $view->current_display;
    $vars['swf_path'] = $base_path . drupal_get_path('module', 'views_fusioncharts_multipleseries') . '/fusioncharts/' . $options['chart_type'] . '.swf';
    $vars['width'] = $options['width'];
    $vars['height'] = $options['height'];
    $vars['config'] = $configstring;
}
