<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/




require_once dirname(__FILE__) . '/views_fusioncharts_common.inc';

function views_fusioncharts_singleseries_init() {
    drupal_add_js(drupal_get_path('module', 'views_fusioncharts_singleseries') .'/fusioncharts/FusionCharts.js');
}

/**
 * Implementation of hook_views_api().
 */
function views_fusioncharts_singleseries_views_api() {
    return array('api' => 3);
}

/**
 * Implementation of hook_views_plugin().
 */
function views_fusioncharts_singleseries_views_plugins() {
    $path = drupal_get_path('module', 'views_fusioncharts_singleseries');
    $theme_path = "$path/theme";
    $config = array(
        'module'  => 'views_fusioncharts_singleseries',
        'style'   => array( // Declare this style plugin.
            'views_fusioncharts_singleseries' => array(
                'title'           => 'FusionCharts (Single-Series)',
                'path'            => $path,
                'help'            => 'Displays views as single-series FusionCharts',
                'handler'         => 'views_plugin_style_fusioncharts_singleseries',
                'theme'           => 'views_views_fusioncharts_singleseries_style',
                'theme path'      => $theme_path,
                'uses row plugin' => FALSE,
                'uses fields'     => TRUE,
                'uses options'    => TRUE,
                'type'            => 'normal',
                'even empty'      => FALSE
            )
        )
    );
    //kpr($config); die();
    return $config;
}

//this is a theme pre-process function where we can prepare variables for the template
function template_preprocess_views_views_fusioncharts_singleseries_style(&$vars) {
    global $base_path;

    $options = $vars['options'];
    $view = $vars['view'];
    $rows_in = $vars['rows'];
    $fields = &$view->field;

    $config = new DOMDocument;
    $chart = $config->createElement('chart');
    $config->appendChild($chart);

    $hasStyle = FALSE;
    $styles = $config->createElement('styles');
    $definition = $config->createElement('definition');
    $application = $config->createElement('application');
    $styles->appendChild($definition);
    $styles->appendChild($application);

    // Captioning
    if (drupal_strlen(trim($options['chart_title'])) > 0) {
        $chart->setAttribute('caption', trim($options['chart_title']));
    }
    if (drupal_strlen(trim($options['chart_subtitle'])) > 0) {
        $chart->setAttribute('subcaption', trim($options['chart_subtitle']));
    }
    // Axes
    if (drupal_strlen(trim($options['xaxisname'])) > 0) {
        $chart->setAttribute('xaxisname', trim($options['xaxisname']));
    }
    if (drupal_strlen(trim($options['yaxisname'])) > 0) {
        $chart->setAttribute('yaxisname', trim($options['yaxisname']));
    }
    if (drupal_strlen(trim($options['yaxismax'])) > 0 && floatval($options['yaxismax']) != 00) {
        $chart->setAttribute('yAxisMaxValue', floatval($options['yaxismax']));
    }
    if (drupal_strlen(trim($options['yaxismin'])) > 0 && floatval($options['yaxismin']) != 00) {
        $chart->setAttribute('yAxisMinValue', floatval($options['yaxismin']));
    }
    if (drupal_strlen(trim($options['yaxisvaluesstep'])) > 0) {
        $chart->setAttribute('yAxisValuesStep', trim($options['yaxisvaluesstep']));
    }

    // Formatting of displayed numeric values
    if (isset($options['values']['show'])) {
        $chart->setAttribute('showValues', intval($options['values']['show']));
    }
    if (isset($options['values']['rotate'])) {
        $chart->setAttribute('rotateValues', intval($options['values']['rotate']));
    }
    if (isset($options['values']['inside'])) {
        $chart->setAttribute('placeValuesInside', intval($options['values']['inside']));
    }

    // General number formatting
    if (isset($options['numformat']['commas']) && intval($options['numformat']['commas']) >= 0) {
        $chart->setAttribute('formatNumber', intval($options['numformat']['commas']));
    }
    if (isset($options['numformat']['abbreviate']) && intval($options['numformat']['abbreviate']) >= 0) {
        $chart->setAttribute('formatNumberScale', intval($options['numformat']['abbreviate']));
    }
    if (isset($options['numformat']['decimals']) && intval($options['numformat']['decimals']) >= 0) {
        $chart->setAttribute('decimals', intval($options['numformat']['decimals']));
    }
    if (isset($options['numformat']['prefix']) && drupal_strlen($options['numformat']['prefix']) > 0) {
        $chart->setAttribute('numberPrefix', trim($options['numformat']['prefix']));
    }
    if (isset($options['numformat']['suffix']) && drupal_strlen($options['numformat']['suffix']) > 0) {
        $chart->setAttribute('numberSuffix', trim($options['numformat']['suffix']));
    }


    // Formatting of column/bar elements
    if (isset($options['column']['shadow'])) {
        $chart->setAttribute('showColumnShadow', intval($options['column']['shadow']));
    }
    if (isset($options['column']['rotate'])) {
        $chart->setAttribute('rotateNames', intval($options['column']['rotate']));
    }

    // Formatting of tooltips
    if (isset($options['tooltips']['bgcolor']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['tooltips']['bgcolor'])) {
        $chart->setAttribute('toolTipBgColor', ltrim(drupal_strtoupper($options['tooltips']['bgcolor']), '#'));
    }
    if (isset($options['tooltips']['border']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['tooltips']['border'])) {
        $chart->setAttribute('toolTipBorderColor', ltrim(drupal_strtoupper($options['tooltips']['border']), '#'));
    }

    // General appearance formatting
    if (isset($options['appearance']['border'])) {
        $chart->setAttribute('showBorder', intval($options['appearance']['border']));
    }
    $bgTop = ltrim(drupal_strtoupper($options['appearance']['bg_top']), '#');
    $bgBottom = ltrim(drupal_strtoupper($options['appearance']['bg_bottom']), '#');
    if (!preg_match('!^[0-9A-F]{6}$!', $bgTop)) {
        $bgTop = 'FFFFFF';
    }
    if (!preg_match('!^[0-9A-F]{6}$!', $bgBottom)) {
        $bgBottom = 'FFFFFF';
    }
    $chart->setAttribute('bgColor', "$bgBottom,$bgTop");

    $alphaTop = intval($options['appearance']['alpha_top']);
    $alphaBottom = intval($options['appearance']['alpha_top']);
    $alphaTop = min(100, max(0, $alphaTop));
    $alphaBottom = min(100, max(0, $alphaBottom));
    $chart->setAttribute('bgAlpha', "$alphaBottom,$alphaTop");

    if (isset($options['appearance']['round'])) {
        $chart->setAttribute('useRoundEdges', intval($options['appearance']['round']));
    }
    if (isset($options['appearance']['showalternate'])) {
        if (strpos($options['chart_type'], 'Bar') !== FALSE) {
            $attribName = 'showAlternateVGridColor';
        }
        else {
            $attribName = 'showAlternateHGridColor';
        }
        $chart->setAttribute($attribName, intval($options['appearance']['showalternate']));
    }
    if (!$rounded && isset($options['appearance']['border_thickness'])) {
        $chart->setAttribute('plotBorderThickness', intval($options['appearance']['border_thickness']));
    }

    if (isset($options['appearance']['animation'])) {
        $chart->setAttribute('animation', intval($options['appearance']['animation']));
    }
    if (isset($options['appearance']['bordercolor'])  && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['appearance']['bordercolor'])) {
        $chart->setAttribute('plotBorderColor', ltrim(drupal_strtoupper($options['appearance']['bordercolor']), '#'));
    }
    if (isset($options['appearance']['linecolor'])  && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['appearance']['linecolor'])) {
        $chart->setAttribute('lineColor', ltrim(drupal_strtoupper($options['appearance']['linecolor']), '#'));
    }
    $chart->setAttribute('plotFillRatio', $options['appearance']['plotgradient'] ? 0 : 100);

    // Canvas Settings
    if (isset($options['canvas']['chartcanvasbgcolor'])) {
        $chart->setAttribute('canvasBgColor', $options['canvas']['chartcanvasbgcolor']);
    }
    if (isset($options['canvas']['chartcanvasbordercolor'])) {
        $chart->setAttribute('canvasBorderColor', $options['canvas']['chartcanvasbordercolor']);
    }
    if (isset($options['canvas']['chartcanvasborderthickness'])) {
        $chart->setAttribute('canvasBorderThickness', intval($options['canvas']['chartcanvasborderthickness']));
    }
    if (isset($options['canvas']['chartcanvasbgalpha'])) {
        $chart->setAttribute('canvasBgAlpha', intval($options['canvas']['chartcanvasbgalpha']));
    }
    if (isset($options['canvas']['chartcanvaspadding'])) {
        $chart->setAttribute('canvasPadding', intval($options['canvas']['chartcanvaspadding']));
    }

    //Anchor Settings- Applicable for  Line Charts
    if (isset($options['anchor']['anchorsides'])) {
        $chart->setAttribute('anchorSides', intval($options['anchor']['anchorsides']));
    }
    if (isset($options['anchor']['anchorradius'])) {
        $chart->setAttribute('anchorRadius', intval($options['anchor']['anchorradius']));
    }
    if (isset($options['anchor']['anchorbgcolor'])) {
        $chart->setAttribute('anchorBgColor', $options['anchor']['anchorbgcolor']);
    }


    // Fonts
    if (isset($options['fonts']['basefamily']) && drupal_strlen(trim($options['fonts']['basefamily'])) > 0) {
        $chart->setAttribute('baseFont', trim($options['fonts']['basefamily']));
    }
    if (isset($options['fonts']['basesize']) && intval($options['fonts']['basesize']) > 0) {
        $chart->setAttribute('baseFontSize', floatval($options['fonts']['basesize']));
    }
    if (isset($options['fonts']['basefontcolor']) && intval($options['fonts']['basefontcolor']) > 0) {
        $chart->setAttribute('baseFontColor', floatval($options['fonts']['basefontcolor']));
    }
    $fontobjects = array('caption', 'datalabels', 'subcaption', 'xaxisname', 'xaxisvalues', 'yaxisname', 'yaxisvalues');
    foreach ($fontobjects as $fontobject) {
        if (views_fusioncharts_add_style($options, $fontobject, $definition, $application)) {
            $hasStyle = TRUE;
        }
    }

    // Dividing lines configuration
    if (isset($options['divlines']['number']) && intval($options['divlines']['number']) > 0) {
        $chart->setAttribute('numDivLines', intval($options['divlines']['number']));
        if (isset($options['divlines']['color']) && preg_match('!^#?[0-9A-Fa-f]{6}$!', $options['divlines']['color'])) {
            $chart->setAttribute('divLineColor', ltrim(drupal_strtoupper($options['divlines']['color']), '#'));
        }
        if (isset($options['divlines']['dashed']) && $options['divlines']['dashed']) {
            $chart->setAttribute('divLineIsDashed', '1');
            if (isset($options['divlines']['dashlen']) && intval($options['divlines']['dashlen']) > 0) {
                $chart->setAttribute('divLineDashLen', intval($options['divlines']['dashlen']));
            }
            if (isset($options['divlines']['dashgap']) && intval($options['divlines']['dashgap']) > 0) {
                $chart->setAttribute('divLineDashGap', intval($options['divlines']['dashgap']));
            }
        }
    }
    //dsm($options);
    // Data fields
    $xfield = views_fusioncharts_get_field_alias($options['xaxisfield'], $fields);
    $yfield = views_fusioncharts_get_field_alias($options['yaxisfield'], $fields);
    $toolfield = isset($options['tooltips']['field']) ? views_fusioncharts_get_field_alias($options['tooltips']['field'], $fields) : NULL;
    $linkfield = isset($options['columns']['linkfield']) ? views_fusioncharts_get_field_alias($options['columns']['linkfield'], $fields) : NULL;
    $colorfield = isset($options['columns']['colorfield']) ? views_fusioncharts_get_field_alias($options['columns']['colorfield'], $fields) : NULL;

    $hasHTMLTooltext = FALSE;
    foreach ($rows_in as $row) {
        $row = views_fusioncharts_views_render_fields($view, $row);
        if (!isset($row->$xfield) || !isset($row->$yfield)) {
            continue;
        }
        $set = $config->createElement('set');
        $set->setAttribute('label', $row->$xfield);
        $set->setAttribute('value', $row->$yfield);
        if (isset($toolfield) && isset($row->$toolfield) && drupal_strlen(trim($row->$toolfield)) > 0) {
            $tooltext = trim($row->$toolfield);
            if (!$hasHTMLTooltext && $tooltext != strip_tags($tooltext)) {
                $hasHTMLTooltext = TRUE;
            }
            $set->setAttribute('toolText', trim(str_replace("\r\n", "\n", $row->$toolfield)));
        }
        if (isset($colorfield) && isset($row->$colorfield) && preg_match('!^[0-9A-F]{6}$!', ltrim($row->$colorfield, '#'))) {
            $set->setAttribute('color', ltrim($row->$colorfield, '#'));
        }
        if (isset($linkfield) && isset($row->$linkfield) && drupal_strlen(trim($row->$linkfield)) > 0) {
            $set->setAttribute('link', trim(str_replace('&amp;', '&', $row->$linkfield)));
        }
        $chart->appendChild($set);
    }
    if ($hasHTMLTooltext) {
        $hasStyle = TRUE;

        $style = $config->createElement('style');
        $style->setAttribute('name', 'tooltip_style');
        $style->setAttribute('type', 'font');
        $style->setAttribute('isHTML', '1');
        $definition->appendChild($style);

        $apply = $config->createElement('apply');
        $apply->setAttribute('toObject', 'TOOLTIP');
        $apply->setAttribute('styles', 'tooltip_style');
        $application->appendChild($apply);
    }

    if ($hasStyle) {
        $chart->appendChild($styles);
    }

    $configString = $config->saveXML($chart);

    $vars['chartID'] = $view->name . '__' . $view->current_display;
    $vars['swf_path'] = $base_path . drupal_get_path('module', 'views_fusioncharts_singleseries') . '/fusioncharts/' . $options['chart_type'] . '.swf';
    $vars['width'] = $options['width'];
    $vars['height'] = $options['height'];
    $vars['config'] = $configString;
}
