<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



/**
 * Implementation of hook_menu to display the smart search form and the auto suggestions
 */
function checkbook_smart_search_menu(){
    $items['smart_search_form'] = array(
    	'title' => '',
    	'page callback' => 'checkbook_smart_search_display',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
    	'type' => MENU_CALLBACK
    );
     $items['smart_search'] = array(
    	'title' => '',
    	'page callback' => '_checkbook_smart_search_get_results',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
    	'type' => MENU_CALLBACK
    );
    $items['smart_search/autocomplete'] = array(
        'page callback' => '_checkbook_smart_search_autocomplete_main_input',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['solr_autocomplete'] = array(
      'page callback' => '_checkbook_smart_search_autocomplete',
      'access callback' => TRUE,
      'file' => 'includes/checkbook_smart_search.inc',
      'type' => MENU_CALLBACK
    );

    $items['smart_search/facet/vendor'] = array(
        'page callback' => '_checkbook_smart_search_vendor_facet',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK,
        'page arguments' => array(4)
    );
    $items['smart_search/autocomplete/expensecategory'] = array(
        'page callback' => '_checkbook_smart_search_expensecategory_autocomplete',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );

    $items['smart_search/autocomplete/fiscalyear'] = array(
        'page callback' => '_checkbook_smart_search_fiscalyear_autocomplete',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['smart_search/autocomplete/regfiscalyear'] = array(
        'page callback' => '_checkbook_smart_search_regfiscalyear_autocomplete',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['exportSmartSearch/form'] = array(
        'page callback' => '_checkbook_smart_search_export_form',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['exportSmartSearch/download'] = array(
        'page callback' => '_checkbook_smart_search_export_download',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['smart_search/autocomplete/industrytype'] = array(
        'page callback' => '_checkbook_smart_search_industrytype_autocomplete',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK
    );
    $items['smart_search/ajax/results'] = array(
        'page callback' => '_checkbook_smart_search_ajax_results',
        'access callback' => TRUE,
        'file' => 'includes/checkbook_smart_search.inc',
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Displays the smart search form
 */

function checkbook_smart_search_display(){
    return drupal_get_form('checkbook_smart_search_form');
}


/**
 * Returns the smart search form
 * @param $form
 * @param $form_state
 * @return mixed
 */
function checkbook_smart_search_form($form, $form_state)
{
  $solr_datasource = _checkbook_get_datasource();
  module_load_include('inc', 'checkbook_smart_search', 'includes/checkbook_smart_search');
  $form['search_box'] = array(
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );
  $form['domain'] = [
    '#type' => 'hidden',
    '#value' => $solr_datasource,
  ];
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('_checkbook_smart_search_submit')
  );
  $form['#attached'] = array(
    'library' => array(
      array('system', 'ui.autocomplete', FALSE)
    ),
    'js' => array(
      'type' => 'file',
      'data' => drupal_get_path('module', 'checkbook_smart_search') . '/js/smart_search.js'
    )
  );

  drupal_add_js(['solr_datasource' => $solr_datasource], 'setting');

  return $form;
}


/** Theme for search results page. **/
function checkbook_smart_search_theme(){
    return array(
        'checkbook_smart_search_results' => array(
            'template' => 'templates/checkbook_smart_search_results',
            'arguments' => array('search_results' => NULL)
        ),
        'search_facets' => array(
            'template' => 'templates/search_facets',
            'arguments' => array('search_facets' => NULL)
        ),
        'revenue' => array(
            'template' => 'templates/revenue',
            'arguments' => array('revenue_results' => NULL)
        ),
        'revenue_budget' => array(
            'template' => 'templates/revenue_budget',
            'arguments' => array('revenue_budget_results' => NULL)
        ),
        'budget' => array(
            'template' => 'templates/budget',
            'arguments' => array('budget_results' => NULL)
        ),
        'spending' => array(
            'template' => 'templates/spending',
            'arguments' => array('spending_results' => NULL)
        ),
        'payroll' => array(
            'template' => 'templates/payroll',
            'arguments' => array('payroll_results' => NULL)
        ),
        'contracts' => array(
            'template' => 'templates/contracts',
            'arguments' => array('contracts_results' => NULL)
        ),
        'facet_results' => array(
            'template' => 'templates/facet_results',
            'arguments' => array('results' => NULL,'name' => NULL)
        ),
        'ajax_results' => array(
            'template' => 'templates/checkbook_smart_search_ajax_results',
            'arguments' => array('results' => NULL,'name' => NULL)
        ),
        'checkbook_smart_search_export_form' => array(
            'template' => 'templates/checkbook_smart_search_export_dialog'
        ) 
    );
}

function checkbook_smart_search_block_info(){
    $blocks['checkbook_smart_search_form'] = array(
        'info' => t('Checkbook Smart Search Form Block'),
    );
    return $blocks;
}

/** Hook to place the smart search form in block. *
 * @param string $delta
 * @return mixed
 */

function checkbook_smart_search_block_view($delta='')
{
    switch($delta) {
        case 'checkbook_smart_search_form':
            $block['subject'] = null;
            $block['content'] = drupal_get_form('checkbook_smart_search_form');
            break;
    }
   return $block;
 }

