<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * Implements hook_menu()
 */

function checkbook_mwbe_agency_grading_menu() {
    $items = array();
    $items['mwbe_agency_grading'] = array(
        'page callback' => '_checkbook_mwbe_agency_grading',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['mwbe_agency_grading/prime_vendor_data'] = array(
        'title' => 'Prime Vendor Data',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );
    $items['mwbe_agency_grading/sub_vendor_data'] = array(
        'title' => 'Sub Vendor Data',
        'page callback' => '_checkbook_mwbe_agency_grading',
        'access callback' => TRUE,
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['mwbe_agency_grading_csv']  = array(
        'type' => MENU_CALLBACK,
        'page callback' => '_checkbook_mwbe_agency_grading_csv',
        'access callback' => TRUE
  		);
    return($items);
}


/**
 * Implements hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function checkbook_mwbe_agency_grading_theme($existing, $type, $theme, $path) {
	return array(
			'mwbe_agency_grading_main' => array(
					'template' => 'templates/mwbe_agency_grading_main',
					'arguments' => array('left_content' => NULL, 'right_content' => NULL)
			),
			'mwbe_agency_grading_right_side_bar' => array(
					'template' => 'templates/mwbe_agency_grading_right_side_bar',
					'arguments' => array()
			),
			'mwbe_agency_grading_left_table' => array(
					'template' => 'templates/mwbe_agency_grading_left_table',
					'arguments' => array()
			),
			'mwbe_agency_grading_row_chart' => array(
					'template' => 'templates/mwbe_agency_grading_row_chart',
					'arguments' => array()
			)
	);
}

function _checkbook_mwbe_agency_grading($data_type = 'prime_vendor_data'){

	$agencies_data =  _checkbook_mwbe_agency_grading_getdata();
	$left_content =  _checkbook_mwbe_agency_grading_left($agencies_data, $data_type);
	$right_content = _checkbook_mwbe_agency_grading_right($agencies_data);
	$links = array(l(t('Home'), ''),'M/WBE Agency Summary');
	drupal_set_breadcrumb($links);
	drupal_set_title("M/WBE Agency Summary");

	return theme('mwbe_agency_grading_main',array('left_content'=>$left_content,'right_content'=>$right_content));
}

function _checkbook_mwbe_agency_grading_left($agencies_data, $data_type){
	
	$left_content_agencies = array();
	$mwbe_cats = _mwbe_agency_grading_current_cats();
	foreach($agencies_data as $row){
		$data_row = array();
		$spending_amount =  0;
		foreach($mwbe_cats as $mwbe_cat){
			$spending_amount += $row[$mwbe_cat];
			$data_row[$mwbe_cat] = $row[$mwbe_cat];
		}	
		$left_content_agencies[] = array('spending_amount'=>$spending_amount,'agency_id'=>$row['agency_id'],'agency_name'=>$row['agency_name'],'data_row'=>$data_row);
	}	
	usort($left_content_agencies,'_checkbook_agency_grading_comp');
	return theme('mwbe_agency_grading_left_table',array('left_agencies_data' => $left_content_agencies, 'data_type' => $data_type));
	
}


function _checkbook_agency_grading_comp($a, $b){
	if ($a['spending_amount'] == $b['spending_amount']) {
		return 0;
	}
	return ($a['spending_amount'] > $b['spending_amount']) ? -1 : 1;
	
}

function _checkbook_mwbe_agency_grading_right($agencies_data){
	
	$nyc_data = array();	
	$nyc_data['agencies'] = count($agencies_data);
	$mwbe_cats = _mwbe_agency_grading_current_cats();
	foreach($agencies_data as $row){		
		$nyc_data['total_mwbe'] += $row['total_mwbe'];
		foreach($mwbe_cats as $cat){
			$nyc_data['total_spending_chart'] += $row[$cat];
		}
		$nyc_data['total_non_mwbe'] += $row['n_mwbe'];
		$nyc_data['total_io'] += $row['io_nonmwbe'];
		$nyc_data['total'] += $row['total_mwbe'] + $row['n_mwbe'] ;
	}
	$nyc_data['mwbe_share'] = custom_number_formatter_format($nyc_data['total_mwbe']/($nyc_data['total_mwbe'] + $nyc_data['total_non_mwbe'] ) * 100,1,null,'%');
	$nyc_data['total_mwbe']	 = custom_number_formatter_format($nyc_data['total_mwbe'],1,'$')	;
	$nyc_data['total_non_mwbe']	 = custom_number_formatter_format($nyc_data['total_non_mwbe'],1,'$')	;
	$nyc_data['total_io']	 = custom_number_formatter_format($nyc_data['total_io'],1,'$')	;
	$nyc_data['total']	 = custom_number_formatter_format($nyc_data['total'],1,'$')	;
	$html_right = theme('mwbe_agency_grading_right_side_bar',array('nyc_data'=>$nyc_data));
	return $html_right;
}

function _checkbook_mwbe_agency_grading_getdata(){

    $is_prime = RequestUtilities::get('mwbe_agency_grading');
    $is_prime_csv = RequestUtilities::get('mwbe_agency_grading_csv');
    if($is_prime == 'sub_vendor_data' || $is_prime_csv == 'sub_vendor_data' ){
        $sql1 = _checkbook_mwbe_agency_grading_generate_sql("aggregateon_subven_spending_coa_entities");
    }else{
       $sql1 = _checkbook_mwbe_agency_grading_generate_sql("aggregateon_mwbe_spending_coa_entities");
    }

    $order='';
    $sortcol='';

    if(!empty($_GET['q'])){
        if(isset($_GET['iSortCol_0'])){
            if($_GET['iSortCol_0'] == 0){
                $sortcol = 'order by a1.agency_name';
            }
            else{
                $sortcol = 'order by a1.ytd_spending';
            }
        }
        else{
            $sortcol = 'order by a1.ytd_spending';
        }

        if(isset($_GET['sSortDir_0'])){
            if($_GET['sSortDir_0'] == 'desc'){
                $order = 'desc';
            }
            else{
                $order = 'asc';
            }
        }
        else{
            $order = 'desc';
        }
    }
    else{
        $sortcol = 'order by a1.ytd_spending';
        $order = 'desc';
    }

	$sql = 'select  a1.agency_name , a1.agency_id,
	coalesce(a1.aa_mwbe,0) aa_mwbe,
	coalesce(a1.ba_mwbe,0)  ba_mwbe,
	coalesce(a1.w_mwbe,0)  w_mwbe,
	coalesce(a1.ha_mwbe,0)  ha_mwbe,
	coalesce(a1.total_mwbe,0)  total_mwbe,
	coalesce(a1.n_mwbe,0)  n_mwbe
	from ( ' . $sql1 . ' ) a1 '
    . $sortcol .' '.$order;
	return  _checkbook_project_execute_sql($sql);

}

function _checkbook_mwbe_agency_grading_generate_sql($table){
	
	$where_filters = array();
	$urlParamMap = array("year_id"=>"year", "type_of_year"=>"yeartype");
    $mwbe_cats = _mwbe_agency_grading_current_cats();
	foreach($urlParamMap as $column=>$path_param){
		$where_filters[] = _widget_build_sql_condition(' a.' . $column, RequestUtilities::get($path_param));
	}

	if(count($where_filters) > 0){
		$where_filter = ' where ' . implode(' and ' , $where_filters);
	}


	$sql = 'select  ra.agency_name , a.agency_id,
    SUM(
       CASE
            WHEN minority_type_id = 4 THEN total_spending_amount
            WHEN minority_type_id = 5 THEN total_spending_amount
            ELSE 0
	END) aa_mwbe,
	SUM(
       CASE
            WHEN minority_type_id = 2 THEN total_spending_amount
            ELSE 0
	END) ba_mwbe,
	SUM(
       CASE
            WHEN minority_type_id = 9 THEN total_spending_amount
            ELSE 0
	END) w_mwbe,
	SUM(
       CASE
            WHEN minority_type_id = 3 THEN total_spending_amount
            ELSE 0
	END) ha_mwbe,
	SUM(
       CASE
            WHEN minority_type_id = 11 THEN total_spending_amount
            ELSE 0
	END) io_mwbe,
	SUM(
       CASE WHEN minority_type_id = 2 THEN total_spending_amount
            WHEN minority_type_id = 3 THEN total_spending_amount
            WHEN minority_type_id = 4 THEN total_spending_amount
            WHEN minority_type_id = 5 THEN total_spending_amount
             WHEN minority_type_id = 9 THEN total_spending_amount
            ELSE 0
	END) total_mwbe,
		SUM(
       CASE
             WHEN minority_type_id = 7 THEN total_spending_amount
            ELSE 0
	END) n_mwbe,';

    $sql .= ' SUM(
    CASE ';
        if(in_array("ba_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 2 THEN total_spending_amount';
        }
        if(in_array("ha_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 3 THEN total_spending_amount';
        }
        if(in_array("aa_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 4 THEN total_spending_amount
                      WHEN minority_type_id = 5 THEN total_spending_amount';
        }
        if(in_array("w_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 9 THEN total_spending_amount';
        }
        if(in_array("n_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 7 THEN total_spending_amount';
        }
        if(in_array("io_mwbe", $mwbe_cats)){
            $sql .= ' WHEN minority_type_id = 11 THEN total_spending_amount';
        }
    $sql .= ' ELSE 0
	END) ytd_spending';
    $sql .= '
        from {' . $table . '} a
    join {ref_agency} ra on ra.agency_id =  a.agency_id
   ' . $where_filter . '
        group by  ra.agency_name,a.agency_id
   ';

    return $sql;
}



function _mwbe_agency_grading_current_cats(){

	if(RequestUtilities::get('mwbe_filter') != null){
		$url_cats = explode('~',RequestUtilities::get('mwbe_filter'));
		return $url_cats;
	}else{
		return array('aa_mwbe','ba_mwbe','ha_mwbe','w_mwbe');
	}

} 


function _checkbook_mwbe_agency_grading_csv(){

	$agencies_data =  _checkbook_mwbe_agency_grading_getdata();
	$data = "Agency, Asian American, Black American, Women, Hispanic American, M/WBE Spending, Non M/WBE";
    $mwbe_cats = _mwbe_agency_grading_current_cats();
	foreach($agencies_data as $row){
        $total = 0;
        foreach($mwbe_cats as $mwbe_cat){
            $total += $row[$mwbe_cat];
        }
        if($total > 0){
            $data .= PHP_EOL;
            $data .=  $row['agency_name'];
            $data .=  "," . $row['aa_mwbe'];
            $data .=  "," . $row['ba_mwbe'];
            $data .=  "," . $row['w_mwbe'];
            $data .=  "," . $row['ha_mwbe'];
            $data .=  "," . $row['total_mwbe'];
            $data .=  "," . $row['n_mwbe'];

        }
    }
	
	drupal_add_http_header("Content-Type", "text/csv");
	drupal_add_http_header("Content-Length",strlen($data));
	drupal_add_http_header("Content-Disposition", "attachment; filename=TransactionsData.csv");
	drupal_add_http_header("Pragma", "cache");
	drupal_add_http_header("Expires", "-1");
	
	echo ($data);
	
}
