<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


/*************************************************************************************/
/* Widget Hooks                                                                      */
/*************************************************************************************/

function widget_phpparser_widget_metadata() {
	return array(
    'phpparser' => array(
      'name' => t('PHPParser'),
      'module' => 'widget_phpparser',
      'description' => t("This widget type implements PHP parsing.")
	)
	);
}


function widget_phpparser_widget_prepare(&$node) {

    if (isset($node->widgetConfig->prepareConfig)) {
        eval($node->widgetConfig->prepareConfig);
    }

}

function widget_phpparser_widget_validate(&$node) {

}

function widget_phpparser_widget_data(&$node) {

}

function widget_phpparser_widget_view(&$node) {
    $code = $node->widgetConfig->phpcode;
    if(isset($code)){
        return eval($code);
    }
    
    $customDataHandlerClass = $node->widgetConfig->customDataHandlerClass;
    if(isset($customDataHandlerClass)){
       $class =  new $customDataHandlerClass();
       $class->getData($node ) ;       
    }

    $template = $node->widgetConfig->template;
    return theme($template, array('node'=> $node));
}
