<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_postgresql_dc_datasource_manipulation() {
    $items[PostgreSQLDataSource::TYPE] = array(
        'handler' => 'DefaultSQLDataSourceManipulationHandler',
        'extensions' => array(
            'prepareManipulationStatementBatch' => 'DefaultPrepareManipulationStatementBatchImpl',

            'prepareInsertStatementBatch' => 'DefaultPrepareInsertStatementBatchImpl',
            'prepareUpdateStatement' => 'DefaultPrepareUpdateStatementImpl',
            'prepareDeleteStatementBatch' => 'DefaultPrepareDeleteStatementImpl'
        )
    );

    return $items;
}
