<?php

/**
 * @file
 * Uninstall functions for the Date All Day Test Feature module.
 */

/**
 * Implements hook_uninstall().
 */
function date_all_day_test_feature_uninstall() {
  // Delete the bundled content types.
  node_type_delete('test_datetime');
  node_type_delete('test_iso_date');
  node_type_delete('test_timestamp');
  variable_del('node_preview_test_datetime_feature');
  variable_del('node_preview_test_iso_date_feature');
  variable_del('node_preview_test_timestamp_feature');
  node_types_rebuild();
  menu_rebuild();
}
