<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


/**
 * Implementation of hook_views_api().
 */
function views_ranking_views_api() {
	return array('api' => 3);
}

/**
 * Implementation of hook_views_plugin().
 */
function views_ranking_views_plugins() {
	$path = drupal_get_path('module', 'views_ranking');
	return array(
    'module'  => 'views_ranking',
      'style'   => array(                 // Declare the views_highcharts style plugin.
        'views_ranking'      => array(
        'title'         => ('Ranking Style'),
	    'path'          => $path,
	    'help'          => ('Displays the rank of the result'), 
        'handler'         => 'views_plugin_style_ranking',
		'theme'           => 'views_views_ranking_style',
	    'theme file'      => 'views_views_ranking_style.theme.inc',
	    'theme path'      => $path.'/theme',
        'uses row plugin' => FALSE,
        'uses fields'     => TRUE,
        'uses options'    => TRUE,
        'type'            => 'normal',
	    'even empty'      => FALSE
	  ),
	),
  );
}

//this is a theme pre-process function where we can prepare varialbes for the template
function template_preprocess_views_views_ranking_style(&$vars) {
	
	$options = $vars['options'];
	log_debug($options);	
	$rows = $vars['rows'];
	$vars['rank'] = $rows[0];
	
}
