<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/** validates strings as UTF-8 to prevent cross site scripting attacks and decodes special characters */
function checkbook_purifynprepare_init() {
    checkbook_purifynprepare_access_denied($_GET['q']);
    $_GET['q'] = check_plain($_GET['q'],array());
    $_GET['q'] = htmlspecialchars_decode ($_GET['q'], ENT_QUOTES);
    if(is_array($_REQUEST)){
        foreach($_REQUEST as $key=>$value){       
            if($key != "checkbookHistoryLinks")   
              checkbook_purifynprepare_access_denied($value);
            $_REQUEST[$key] = check_plain($value,array());
            
        }
    }
}


function checkbook_purifynprepare_access_denied($value){

//  if(preg_match("/((\%3C)|<|(\%2b)|(\+))[^\n]+((\%3E)|>|(\%2b))|(\+)/", $value)){
//    //TODO
//     //drupal_goto("");
//  }
}