<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_postgresql_dc_datasource() {
    $items[PostgreSQLDataSource::TYPE] = array(
        'extensions' => array(
            'getMaximumEntityNameLength' => 'PostgreSQLMaximumEntityNameLengthImpl',

            'concatenateValues' => 'DefaultConcatenateValuesImpl',
            'formatWildcardValue' => 'PostgreSQLFormatWildcardValueImpl',
            'formatDateValue' => 'PostgreSQLFormatDateValueImpl',
            'formatRegularExpression' => 'PostgreSQLRegularExpressionValueImpl',
            'formatNotRegularExpression' => 'PostgreSQLNotRegularExpressionValueImpl',

            'initializeConnection' => 'PostgreSQLInitializeConnectionImpl',
            'executeStatement' => 'PDOExecuteStatementImpl',
            'executeQueryStatement' => 'PDOExecuteQueryStatementImpl',
            'executeQueryStatement_callback' => 'PostgreSQLQueryStatementExecutionCallback',

            'startTransaction' => 'DefaultStartTransactionStatementImpl',
            'commitTransaction' => 'DefaultCommitTransactionStatementImpl',
            'rollbackTransaction' => 'DefaultRollbackTransactionStatementImpl',

            'getDataSourceOwner' => 'PostgreSQLDataSourceOwnerImpl'
        )
    );

    return $items;
}

function data_controller_postgresql_dc_datasource_query() {
    $items[PostgreSQLDataSource::TYPE] = array(
        'handler' => 'DefaultSQLDataSourceQueryHandler',
        'extensions' => array(
            'isJoinSupported' => 'DefaultCheckJoinSupportImpl',
            'applyPagination' => 'DefaultApplyPaginationImpl'
        )
    );

    return $items;
}
