<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
*
* Copyright (C) 2012, 2013 New York City
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/




require_once('common/drupal/EntityQueryHelper.php');
require_once('common/drupal/NodeFieldHelper.php');
require_once('common/object/comparator/SortHelper.php');
require_once('common/object/manipulation/PaginationHelper.php');
require_once('common/pattern/singleton/AbstractSingleton.php');

function data_controller_init() {
    // initializing environment configuration
    Environment::getInstance();
}

// -------------------- Data Controller ------------------------------------------------------------
/**
 * @return DataQueryController
 */
function data_controller_get_instance() {
    return DataQueryControllerProxy::getInstance();
}


// -------------------- Cache Handler --------------------------------------------------------------
function data_controller_dc_cache() {
    $items[InMemoryCacheHandler::$CACHE__TYPE] = array(
        'classname' => 'InMemoryCacheHandler');

    return $items;
}


// -------------------- Data Types -----------------------------------------------------------------
function data_controller_dc_data_type() {
    $items[StringDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('String'),
        'classname' => 'StringDataTypeHandler');
    $items[IntegerDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Integer'),
        'classname' => 'IntegerDataTypeHandler');
    $items[NumberDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Number'),
        'classname' => 'NumberDataTypeHandler');
    $items[CurrencyDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Currency'),
        'classname' => 'CurrencyDataTypeHandler');
    $items[PercentDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Percent'),
        'classname' => 'PercentDataTypeHandler');
    $items[DateDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Date'),
        'classname' => 'DateDataTypeHandler');
/*
    $items[TimeDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Time'),
        'classname' => 'TimeDataTypeHandler');
*/
    $items[DateTimeDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('Datetime'),
        'classname' => 'DateTimeDataTypeHandler');
    $items[URIDataTypeHandler::$DATA_TYPE] = array(
        'description' => t('URI'),
        'classname' => 'URIDataTypeHandler');

    return $items;
}


// -------------------- Data Source Operators ------------------------------------------------------
function data_controller_get_operator_factory_instance() {
    return OperatorFactory::getInstance();
}

function data_controller_dc_datasource_operator() {
    $items[EmptyOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Empty'),
        'handler' => array(
            'classname' => 'EmptyOperatorHandler'));
    $items[NotEmptyOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Not Empty'),
        'handler' => array(
            'classname' => 'NotEmptyOperatorHandler'));

    // value-based operators
    $items[EqualOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Equal'),
        'handler' => array(
            'classname' => 'EqualOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[NotEqualOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Not Equal'),
        'handler' => array(
            'classname' => 'NotEqualOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[GreaterOrEqualOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Greater or Equal'),
        'handler' => array(
            'classname' => 'GreaterOrEqualOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[GreaterThanOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Greater than'),
        'handler' => array(
            'classname' => 'GreaterThanOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[LessOrEqualOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Less or Equal'),
        'handler' => array(
            'classname' => 'LessOrEqualOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[LessThanOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Less than'),
        'handler' => array(
            'classname' => 'LessThanOperatorHandler'),
        'metadata' => array(
            'classname' => 'ValueBasedOperatorMetaData'));
    $items[WildcardOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Wildcard'),
        'handler' => array(
            'classname' => 'WildcardOperatorHandler'),
        'metadata' => array(
            'classname' => 'WildcardOperatorMetaData'));
    $items[NotWildcardOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Not Wildcard'),
        'handler' => array(
            'classname' => 'NotWildcardOperatorHandler'),
        'metadata' => array(
            'classname' => 'WildcardOperatorMetaData'));
    $items[RegularExpressionOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Regular Expression'),
        'handler' => array(
            'classname' => 'RegularExpressionOperatorHandler'),
        'metadata' => array(
            'classname' => 'RegularExpressionOperatorMetaData'));
    $items[NotRegularExpressionOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Regular Expression'),
        'handler' => array(
            'classname' => 'NotRegularExpressionOperatorHandler'),
        'metadata' => array(
            'classname' => 'RegularExpressionOperatorMetaData'));

    // Range-based operators
    $items[RangeOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Range'),
        'handler' => array(
            'classname' => 'RangeOperatorHandler'),
        'metadata' => array(
            'classname' => 'RangeBasedOperatorMetaData'));
    $items[NotInRangeOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Not in Range'),
        'handler' => array(
            'classname' => 'NotInRangeOperatorHandler'),
        'metadata' => array(
            'classname' => 'RangeBasedOperatorMetaData'));
    $items[DynamicRangeOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Dynamic Range'),
        'handler' => array(
            'classname' => 'DynamicRangeOperatorHandler'),
        'metadata' => array(
            'classname' => 'RangeBasedOperatorMetaData'));

    // Data-related operators
    $items[OldestOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Oldest'),
        'handler' => array(
            'classname' => 'OldestOperatorHandler'));
    $items[PreviousOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Previous'),
        'handler' => array(
            'classname' => 'PreviousOperatorHandler'),
        'metadata' => array(
            'classname' => 'PreviousOperatorMetaData'));
    $items[LatestOperatorHandler::$OPERATOR__NAME] = array(
        'description' => t('Latest'),
        'handler' => array(
            'classname' => 'LatestOperatorHandler'));

    return $items;
}


// -------------------- Meta Model -----------------------------------------------------------------
/**
 * @return EnvironmentMetaModel
 */
function data_controller_get_environment_metamodel() {
    return EnvironmentMetaModelFactory::getInstance()->getMetaModel();
}

/**
 * @return MetaModel
 */
function data_controller_get_metamodel() {
    return MetaModelFactory::getInstance()->getMetaModel();
}
