<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (C) 2012, 2013 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*including checkbook_autocomplete_functions.inc file from checkbook_autocomplete for some common functions*/
module_load_include('inc', 'checkbook_autocomplete', 'includes/checkbook_autocomplete_functions');

/**
 * Implements hook_menu()
 *
 * @return array
 */

function checkbook_advanced_search_autocomplete_menu()
{
    $items = array();

    //Spending autocomplete paths
//    $items['advanced-search/autocomplete/spending/payee'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_payee',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/spending/contractno'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_contractno',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    $items['advanced-search/autocomplete/spending/department'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_spending_department',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
//    $items['advanced-search/autocomplete/spending/capitalproject'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_capitalproject',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    $items['advanced-search/autocomplete/spending/expcategory'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_spending_expcategory',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
//    $items['advanced-search/autocomplete/spending/expenseid'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_expenseid',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/spending/entitycontractnum'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_entitycontractnum',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/spending/commodityline'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_commodityline',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/spending/budgetname'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_spending_budgetname',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    //payroll autocomplete paths
//    $items['advanced-search/autocomplete/payroll/employee-name'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_payroll_employee_name',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    //Contracts autocomplete paths
//    $items['advanced-search/autocomplete/contracts/vendor-name'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_vendor_name',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/contract-num'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_contract_number',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/apt-pin'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_apt_pin',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/pin'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_pin',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/entity_contract_number'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_entitycontractnum',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/commodity_line'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_commodityline',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/contracts/budget_name'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_contracts_budgetname',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    //NYCHA Contracts Auto-completes
//    $items['advanced-search/autocomplete/nycha_contracts'] = array(
//        'page callback' => '_checkbook_autocomplete_nycha_contracts',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    // Budget autocomplete paths
//    $items['advanced-search/autocomplete/budget/agency'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_budget_agency',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    $items['advanced-search/autocomplete/budget/department'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_department',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/expcategory'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_expcategory',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/budgetcode'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_budgetcode',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/budgetname'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_budgetname',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/fundingsrc'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_fundingsrc',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/revcat'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_revcat',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/revsrc'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_revsrc',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );

    //Revenue autocomplete paths
//    $items['advanced-search/autocomplete/revenue/revenueclass'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_revenue_revenueclass',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
//    $items['advanced-search/autocomplete/revenue/revenuesource'] = array(
//        'page callback' => '_checkbook_advanced_search_autocomplete_revenue_revenuesource',
//        'access callback' => TRUE,
//        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
//        'type' => MENU_CALLBACK
//    );
    return $items;
}
