<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (C) 2012, 2013 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*including checkbook_autocomplete_functions.inc file from checkbook_autocomplete for some common functions*/
module_load_include('inc', 'checkbook_autocomplete', 'includes/checkbook_autocomplete_functions');

/**
 * Implements hook_menu()
 *
 * @return array
 */

function checkbook_advanced_search_autocomplete_menu()
{
    $items = array();

    //Spending autocomplete paths
    $items['advanced-search/autocomplete/spending/department'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_spending_department',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/spending/expcategory'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_spending_expcategory',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );

    // Budget autocomplete paths
    $items['advanced-search/autocomplete/budget/department'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_department',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/expcategory'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_expcategory',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/budgetcode'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_budgetcode',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/budgetname'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_budgetname',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/fundingsrc'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_fundingsrc',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/revcat'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_revcat',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );
    $items['advanced-search/autocomplete/budget/revsrc'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_budget_revsrc',
        'access callback' => TRUE,
        'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
        'type' => MENU_CALLBACK
    );

    //Payroll Years
    $items['payroll/years'] = array(
      'page callback' => '_checkbook_advanced_search_get_payroll_years',
      'access callback' => TRUE,
      'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
      'type' => MENU_CALLBACK
    );
    return $items;
}
