<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/



/*including checkbook_autocomplete_functions.inc file from checkbook_autocomplete for some common functions*/
module_load_include('inc','checkbook_autocomplete','includes/checkbook_autocomplete_functions');

/**
 * Implements hook_menu()
 *
 * @return array
 */

function checkbook_advanced_search_autocomplete_menu() {
  $items = array();
  //Spending autocomplete paths
  $items['advanced-search/autocomplete/spending/payee'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_payee',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/spending/contractno'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_contractno',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/spending/department'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_department',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/spending/capitalproject'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_capitalproject',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/spending/expcategory'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_expcategory',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/spending/expenseid'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_spending_expenseid',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  //payroll autocomplete paths
  $items['advanced-search/autocomplete/payroll/employee-name'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_payroll_employee_name',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  //Contracts autocomplete paths
  $items['advanced-search/autocomplete/contracts/vendor-name'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_contracts_vendor_name',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/contracts/contract-num'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_contracts_contract_number',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/contracts/apt-pin'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_contracts_apt_pin',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/contracts/pin'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_contracts_pin',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  // Budget autocomplete paths
  $items['advanced-search/autocomplete/budget/agency'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_agency',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/department'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_department',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/expcategory'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_expcategory',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/budgetcode'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_budgetcode',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/fundingsrc'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_fundingsrc',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/revcat'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_revcat',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/budget/revsrc'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_budget_revsrc',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  
  //Revenue autocomplete paths
  $items['advanced-search/autocomplete/revenue/revenueclass'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_revenue_revenueclass',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['advanced-search/autocomplete/revenue/revenuesource'] = array(
    'page callback' => '_checkbook_advanced_search_autocomplete_revenue_revenuesource',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_advanced_search_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  return $items;
}
