<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/

/** validates strings as UTF-8 to prevent cross site scripting attacks and decodes special characters */
function checkbook_purifynprepare_init() {

    $_GET['q'] = check_plain($_GET['q'],array());
    $_GET['q'] = htmlspecialchars_decode ($_GET['q'], ENT_QUOTES);
    if(is_array($_REQUEST)){
        foreach($_REQUEST as $key=>$value){
            $_REQUEST[$key] = check_plain($value,array());
        }
    }
}
