<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/**
 * Implementation of hook_menu..
 * @return multitype:string boolean multitype:number
 */
function checkbook_custom_template_menu(){
    $items['checkbook/view_all_popup_template/revenue_category/node/%node'] = array(
        'page callback' => '_checkbook_custom_template_view_all_popup_template',
        'page arguments' => array(4,'revcat'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['checkbook/view_all_popup_template_data/revenue_category/node/%node'] = array(
             'page callback' => '_checkbook_custom_template_view_all_popup_template_data',
             'page arguments' => array(4,'revcat'),
             'access callback' => true,
     	    'type'=>MENU_CALLBACK
    );
    $items['checkbook/view_all_popup_template/funding_source/node/%node'] = array(
        'page callback' => '_checkbook_custom_template_view_all_popup_template',
        'page arguments' => array(4,'fundsrccode'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['checkbook/view_all_popup_template_data/funding_source/node/%node'] = array(
             'page callback' => '_checkbook_custom_template_view_all_popup_template_data',
             'page arguments' => array(4,'fundsrccode'),
             'access callback' => true,
     	    'type'=>MENU_CALLBACK
    );
    $items['checkbook/view_all_popup_template/agency_revenue/node/%node'] = array(
        'page callback' => '_checkbook_custom_template_view_all_popup_template',
        'page arguments' => array(4,'agency'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['checkbook/view_all_popup_template_data/agency_revenue/node/%node'] = array(
             'page callback' => '_checkbook_custom_template_view_all_popup_template_data',
             'page arguments' => array(4,'agency'),
             'access callback' => true,
     	    'type'=>MENU_CALLBACK
    );
    $items['checkbook/view_all_popup_template/dept_revenue/node/%node'] = array(
        'page callback' => '_checkbook_custom_template_view_all_popup_template',
        'page arguments' => array(4,'dept'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['checkbook/view_all_popup_template_data/dept_revenue/node/%node'] = array(
             'page callback' => '_checkbook_custom_template_view_all_popup_template_data',
             'page arguments' => array(4,'dept'),
             'access callback' => true,
     	    'type'=>MENU_CALLBACK
    );
    $items['ajaxData/revenue_category/node/%node'] = array(
        'page callback' => '_checkbook_revenue_get_data',
        'page arguments' => array(3,'revcat'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
  	$items['ajaxData/funding_source/node/%node'] = array(
        'page callback' => '_checkbook_revenue_get_data',
        'page arguments' => array(3,'fundsrccode'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
  	$items['ajaxData/agency_revenue/node/%node'] = array(
        'page callback' => '_checkbook_revenue_get_data',
        'page arguments' => array(3,'agency'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['ajaxData/dept_revenue/node/%node'] = array(
        'page callback' => '_checkbook_revenue_get_data',
        'page arguments' => array(3,'dept'),
        'access callback' => true,
	    'type'=>MENU_CALLBACK
  	);
    $items['ajaxData/budget_top_agencies_by_percent_difference/node/%node'] = array(
            'page callback' => '_checkbook_get_agency_budget_percent_difference',
            'page arguments' => array(3,'agency'),
            'access callback' => true,
    	    'type'=>MENU_CALLBACK
      	);
  	return $items;
}

/**
 * Hook to load custom project specific utility functions during bootstrap..
 */
function checkbook_custom_template_init(){
	require_once(drupal_get_path("module","checkbook_custom_template") . "/includes/checkbook_custom_template.inc");
}

/**
 * Implementation of hook_theme() ...
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function checkbook_custom_template_theme($existing, $type, $theme, $path){
    return [
        'revenue_cat_table' => [
            'template' => 'templates/revenue_category',
            'arguments' => ['node' => NULL]
        ],
        'revenue_fundsrc_table' => [
            'template' => 'templates/revenue_fndsrc',
            'arguments' => ['node' => NULL]
        ],
        'agency_revenue_table' => [
            'template' => 'templates/agency_revenue',
            'arguments' => ['node' => NULL]
        ],
        'dept_revenue_table' => [
            'template' => 'templates/dept_revenue',
            'arguments' => ['node' => NULL]
        ],
        'budget_agency_percent_difference' => [
            'template' => 'templates/budget/agency_percent_difference',
            'arguments' => ['node' => NULL]
        ],

    ];

}
