<?php

use Drupal\checkbook_log\LogHelper;

/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (c) 2012 – 2023 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Implements hook_cron().
 */
function checkbook_api_ref_cron() {
  LogHelper::log_notice("Running checkbook_api_ref_cron");
  $CES = new \Drupal\checkbook_api_ref\API\CheckbookApiRef();
  return $CES->api_ref_cron();
}

/**
 * Implements hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function checkbook_api_ref_mail($key, &$message, $params) {
  $CES = new \Drupal\checkbook_api_ref\API\CheckbookApiRef();
  $CES->gatherData($message);
  $message['body'] = array_merge($message['body'], $params);
}

/**
 * Implements hook_mail_alter().
 *
 * Adds priority headers to messages passing condition.
 * @param $message
 * @throws Exception
 */
function checkbook_api_ref_mail_alter(&$message) {
  // Apply this hook only for `checkbook_etl_status` module
  if ('checkbook_api_ref' !== $message['module']) {
    return;
  }

  if (stripos($message['subject'], 'Fail') || stripos($message['subject'], 'not Found')) {
    $message['headers']['X-Priority'] = '1 (Highest)';
    $message['headers']['X-MSMail-Priority'] = 'High';
    $message['headers']['Importance'] = 'High';
  }

  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  $body_data = array (
    '#theme' => 'api-ref-mail',
    '#message' => $message['body'],
    '#allowed_tags' => ['html','head', 'body', 'main','style', 'header', 'footer','table','tbody','tr','th','td','main','br','a','img'],
  );
  $message['body'] = [\Drupal::service('renderer')->render($body_data)];
  return $message;
}

/**
 * Implements hook_theme()
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function checkbook_api_ref_theme($existing, $type, $theme, $path) {
  return [
    'api-ref-mail'=>[
      'template'=>'api-ref.email',
      'variables' => [
        'file_generation_status' => NULL,
        'message' => []
      ],
    ],
  ];
}
