<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_datasource_python_dc_datasource() {
    $items[PythonDataSource::TYPE] = array(
        'extensions' => array(
            'getMaximumEntityNameLength' => 'UnlimitedEntityNameLengthImpl'
        )
    );

    return $items;
}

function data_controller_datasource_python_dc_datasource_query() {
    $items[PythonDataSource::TYPE] = array(
        'handler' => 'PythonDataSourceHandler');

    return $items;
}
