<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_dimension_reference_dc_dataset_assembler() {
    /*
     * There is no configuration for this assembler
     */
    $items[ReferenceDimensionDatasetAssembler::$DATASET_SOURCE_ASSEMBLER__TYPE] = array(
        'classname' => 'ReferenceDimensionDatasetAssembler');

    return $items;
}
