<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/




function join_controller_get_instance($method) {
    return JoinControllerFactory::getInstance()->getHandler($method);
}

function join_controller_get_supported_methods() {
    return JoinControllerFactory::getInstance()->getSupportedMethods();
}

function join_controller_jc_method() {
    $items[InnerJoinController::$METHOD_NAME] = array(
        'classname' => 'InnerJoinController');
    $items[LeftOuterJoinController::$METHOD_NAME] = array(
        'classname' => 'LeftOuterJoinController');
    $items[RightOuterJoinController::$METHOD_NAME] = array(
        'classname' => 'RightOuterJoinController');
    $items[FullJoinController::$METHOD_NAME] = array(
        'classname' => 'FullJoinController');
    $items[CrossJoinController::$METHOD_NAME] = array(
        'classname' => 'CrossJoinController');
    $items[UnionJoinController::$METHOD_NAME] = array(
        'classname' => 'UnionJoinController');

    return $items;
}
