<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (c) 2012 – 2023 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use Drupal\join_controller\Controller\Handler\CrossJoinController;
use Drupal\join_controller\Controller\Handler\FullJoinController;
use Drupal\join_controller\Controller\Handler\InnerJoinController;
use Drupal\join_controller\Controller\Handler\LeftOuterJoinController;
use Drupal\join_controller\Controller\Handler\RightOuterJoinController;
use Drupal\join_controller\Controller\Handler\UnionJoinController;
use Drupal\join_controller\JoinControllerFactory;

function join_controller_get_instance($method) {
    return JoinControllerFactory::getInstance()->getHandler($method);
}

function join_controller_get_supported_methods() {
    return JoinControllerFactory::getInstance()->getSupportedMethods();
}

function join_controller_jc_method() {
    $items[InnerJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\InnerJoinController');
    $items[LeftOuterJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\LeftOuterJoinController');
    $items[RightOuterJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\RightOuterJoinController');
    $items[FullJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\FullJoinController');
    $items[CrossJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\CrossJoinController');
    $items[UnionJoinController::$METHOD_NAME] = array(
        'classname' => '\Drupal\join_controller\Controller\Handler\UnionJoinController');

    return $items;
}
