CREATE SEQUENCE seq_oge_contract_id;
CREATE SEQUENCE seq_edc_contract_id;
CREATE SEQUENCE seq_tdc_contract_id;



DROP TABLE IF EXISTS edc_contract;
CREATE TABLE edc_contract (
    edc_contract_id integer  PRIMARY KEY DEFAULT nextval('seq_edc_contract_id'::regclass) NOT NULL,
	agency_code character varying(4),
	fms_contract_number character varying,
	fms_commodity_line integer,
	is_sandy_related character varying(3),
	edc_contract_number varchar(15),
	purpose varchar(75),
	budget_name varchar(75),
	edc_registered_amount numeric(16,2),
	vendor_name varchar(150),
	vendor_address varchar(75),
	vendor_city varchar(60),
	vendor_state varchar(25),
	vendor_zip varchar(25),
	agency_id smallint,
	vendor_id integer,
	department_id integer,
	agency_history_id smallint,
	vendor_history_id integer,
	department_history_id integer,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;

DROP TABLE IF EXISTS tdc_contract;
CREATE TABLE tdc_contract (
    tdc_contract_id integer  PRIMARY KEY DEFAULT nextval('seq_tdc_contract_id'::regclass) NOT NULL,
	agency_code character varying(4),
	fms_contract_number character varying,
	fms_commodity_line integer,
	is_sandy_related character varying(3),
	tdc_contract_number varchar(15),
	purpose varchar(75),
	budget_name varchar(75),
	tdc_registered_amount numeric(16,2),
	vendor_name varchar(150),
	vendor_address varchar(75),
	vendor_city varchar(60),
	vendor_state varchar(25),
	vendor_zip varchar(25),
	agency_id smallint,
	vendor_id integer,
	department_id integer,
	agency_history_id smallint,
	vendor_history_id integer,
	department_history_id integer,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS oge_contract;
CREATE TABLE oge_contract (
    oge_contract_id integer  PRIMARY KEY DEFAULT nextval('seq_oge_contract_id'::regclass) NOT NULL,
	agency_code character varying(4),
	fms_contract_number character varying,
	fms_commodity_line integer,
	is_sandy_related character varying(3),
	oge_contract_number varchar(15),
	purpose varchar(75),
	budget_name varchar(75),
	oge_registered_amount numeric(16,2),
	original_amount numeric(16,2),
	current_amount numeric(16,2),
	current_amount_commodity_level numeric(16,2),
	vendor_name varchar(150),
	vendor_address varchar(75),
	vendor_city varchar(60),
	vendor_state varchar(25),
	vendor_zip varchar(25),
	agency_id smallint,
	vendor_id integer,
	department_id integer,
	agency_history_id smallint,
	vendor_history_id integer,
	department_history_id integer,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;



DROP TABLE IF EXISTS oge_contract_previous_load;
CREATE TABLE oge_contract_previous_load (
    oge_contract_id integer  NOT NULL,
	agency_code character varying(4),
	fms_contract_number character varying,
	fms_commodity_line integer,
	is_sandy_related character varying(3),
	oge_contract_number varchar(15),
	purpose varchar(75),
	budget_name varchar(75),
	oge_registered_amount numeric(16,2),
	original_amount numeric(16,2),
	current_amount numeric(16,2),
	current_amount_commodity_level numeric(16,2),
	vendor_name varchar(150),
	vendor_address varchar(75),
	vendor_city varchar(60),
	vendor_state varchar(25),
	vendor_zip varchar(25),
	agency_id smallint,
	vendor_id integer,
	department_id integer,
	agency_history_id smallint,
	vendor_history_id integer,
	department_history_id integer,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;

DROP TABLE IF EXISTS oge_contract_history;
CREATE TABLE oge_contract_history (
    oge_contract_id integer  NOT NULL,
	agency_code character varying(4),
	fms_contract_number character varying,
	fms_commodity_line integer,
	is_sandy_related character varying(3),
	oge_contract_number varchar(15),
	purpose varchar(75),
	budget_name varchar(75),
	oge_registered_amount numeric(16,2),
	original_amount numeric(16,2),
	current_amount numeric(16,2),
	current_amount_commodity_level numeric(16,2),
	vendor_name varchar(150),
	vendor_address varchar(75),
	vendor_city varchar(60),
	vendor_state varchar(25),
	vendor_zip varchar(25),
	agency_id smallint,
	vendor_id integer,
	department_id integer,
	agency_history_id smallint,
	vendor_history_id integer,
	department_history_id integer,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS oge_contract_vendor_level;
CREATE TABLE oge_contract_vendor_level (	
	fms_contract_number character varying,	
	agency_code character varying(4),
	agency_id smallint,
	agency_name character varying(100),
	agency_history_id smallint,
	vendor_id integer,
	vendor_history_id integer,
	vendor_name varchar(150),
	original_amount numeric(16,2),
	current_amount numeric(16,2)
) ;

DROP TABLE IF EXISTS oge_contract_contract_level;
CREATE TABLE oge_contract_contract_level (	
	fms_contract_number character varying,	
	agency_code character varying(4),
	agency_id smallint,
	agency_name character varying(100),
	agency_history_id smallint,
	original_amount numeric(16,2),
	current_amount numeric(16,2)
) ;


/*
 gpfdist -d /vol2share/NYC/FEEDS/EDC/GPFDIST_DIR/ -p 8082 -l /vol2share/NYC/FEEDS/EDC/GPFDIST_DIR/log
 */


DROP TABLE IF EXISTS disbursement_edc;
CREATE TABLE disbursement_edc (
    disbursement_id integer  PRIMARY KEY NOT NULL,
    document_code_id smallint,
    agency_history_id smallint,
    document_id character varying(20),
    document_version integer,
    disbursement_number character varying(40),
    record_date_id int,
    budget_fiscal_year smallint,
    document_fiscal_year smallint,
    document_period character(2),
    check_eft_amount_original numeric(16,2),
    check_eft_amount numeric(16,2),
    check_eft_issued_date_id int,
    check_eft_record_date_id int,
    expenditure_status_id smallint,
    expenditure_cancel_type_id smallint,
    expenditure_cancel_reason_id integer,
    total_accounting_line_amount_original numeric(16,2),
    total_accounting_line_amount numeric(16,2),
    vendor_history_id integer,
    retainage_amount_original numeric(16,2),
    retainage_amount numeric(16,2),
    privacy_flag char(1),
    vendor_org_classification smallint,
    bustype_mnrt varchar(4),
	bustype_mnrt_status smallint,
	minority_type_id smallint,
	bustype_wmno varchar(4),
	bustype_wmno_status smallint,
	bustype_locb varchar(4),
	bustype_locb_status smallint,
	bustype_eent varchar(4),
	bustype_eent_status smallint,
	bustype_exmp varchar(4),
	bustype_exmp_status smallint,
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS disbursement_line_item_edc;

CREATE TABLE disbursement_line_item_edc (
    disbursement_line_item_id bigint  PRIMARY KEY  NOT NULL,
    disbursement_id integer,
    line_number integer,
    disbursement_number character varying(40),
    budget_fiscal_year smallint,
    fiscal_year smallint,
    fiscal_period character(2),
    fund_class_id smallint,
    agency_history_id smallint,
    department_history_id integer,
    expenditure_object_history_id integer,
    budget_code_id integer,
    fund_code varchar(4),
    reporting_code character varying(15),
    check_amount_original numeric(16,2),
    check_amount numeric(16,2),
    agreement_id bigint,
    agreement_accounting_line_number integer,
    agreement_commodity_line_number integer,
    agreement_vendor_line_number integer, 
    reference_document_number character varying,
    reference_document_code varchar(8),
    location_history_id integer,
    retainage_amount_original numeric(16,2),
    retainage_amount numeric(16,2),
    check_eft_issued_nyc_year_id smallint,
    file_type char(1),
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
   );
   
   
   DROP TABLE IF EXISTS disbursement_line_item_details_edc;   
   CREATE TABLE disbursement_line_item_details_edc(
	disbursement_line_item_id bigint,
	disbursement_id integer,
	line_number integer,
	disbursement_number character varying(40),
	check_eft_issued_date_id int,
	check_eft_issued_nyc_year_id smallint,
	fiscal_year smallint,
	check_eft_issued_cal_month_id int,
	agreement_id bigint,
	master_agreement_id bigint,
	fund_class_id smallint,
	check_amount numeric(16,2),
	agency_id smallint,
	agency_history_id smallint,
	agency_code varchar(20),
	expenditure_object_id integer,
	vendor_id integer,
	department_id integer,
	maximum_contract_amount numeric(16,2),
	maximum_contract_amount_cy numeric(16,2),
	maximum_spending_limit numeric(16,2),
	maximum_spending_limit_cy numeric(16,2),
	document_id varchar(20),
	vendor_name varchar,
	vendor_customer_code varchar(20), 
	check_eft_issued_date date,
	agency_name varchar(100),	
	agency_short_name character varying(15),  	
	location_name varchar,
	location_code varchar(4),
	department_name varchar(100),
	department_short_name character varying(15),
	department_code varchar(20),
	expenditure_object_name varchar(40),
	expenditure_object_code varchar(4),
	budget_code_id integer,
	budget_code varchar(10),
	budget_name varchar(60),
	contract_number varchar,
	master_contract_number character varying,
	master_child_contract_number character varying,
  	contract_vendor_id integer,
  	contract_vendor_id_cy integer,
  	master_contract_vendor_id integer,
  	master_contract_vendor_id_cy integer,
  	contract_agency_id smallint,
  	contract_agency_id_cy smallint,
  	master_contract_agency_id smallint,
  	master_contract_agency_id_cy smallint,
  	master_purpose character varying,
  	master_purpose_cy character varying,
	purpose varchar,
	purpose_cy varchar,
	master_child_contract_agency_id smallint,
	master_child_contract_agency_id_cy smallint,
	master_child_contract_vendor_id integer,
	master_child_contract_vendor_id_cy integer,
	reporting_code varchar(15),
	location_id integer,
	fund_class_name varchar(50),
	fund_class_code varchar(5),
	spending_category_id smallint,
	spending_category_name varchar,
	calendar_fiscal_year_id smallint,
	calendar_fiscal_year smallint,
	agreement_accounting_line_number integer,
	agreement_commodity_line_number integer,
	agreement_vendor_line_number integer, 
	reference_document_number character varying,
	reference_document_code varchar(8),
	contract_document_code varchar(8),
	master_contract_document_code varchar(8),
	file_type char(1),
	load_id integer,
	last_modified_date timestamp without time zone,
	job_id bigint
);


DROP TABLE IF EXISTS history_agreement_edc;
CREATE TABLE history_agreement_edc (
    agreement_id bigint  PRIMARY KEY  NOT NULL,
    master_agreement_id bigint,
    document_code_id smallint,
    agency_history_id smallint,
    document_id character varying(20),
    document_version integer,
    tracking_number character varying(30),
    record_date_id int,
    budget_fiscal_year smallint,
    document_fiscal_year smallint,
    document_period character(2),
    description character varying(60),
    actual_amount_original numeric(16,2),
    actual_amount numeric(16,2),
    obligated_amount_original numeric(16,2),
    obligated_amount numeric(16,2),
    maximum_contract_amount_original numeric(16,2),
    maximum_contract_amount numeric(16,2),
    amendment_number character varying(19),
    replacing_agreement_id bigint,
    replaced_by_agreement_id bigint,
    award_status_id smallint,
    procurement_id character varying(20),
    procurement_type_id smallint,
    effective_begin_date_id int,
    effective_end_date_id int,
    reason_modification character varying,
    source_created_date_id int,
    source_updated_date_id int,
    document_function_code varchar,
    award_method_id smallint,
    award_level_code varchar,
    agreement_type_id smallint,
    contract_class_code character varying(2),
    award_category_id_1 smallint,
    award_category_id_2 smallint,
    award_category_id_3 smallint,
    award_category_id_4 smallint,
    award_category_id_5 smallint,
    number_responses integer,
    location_service character varying(255),
    location_zip character varying(10),
    borough_code character varying(10),
    block_code character varying(10),
    lot_code character varying(10),
    council_district_code character varying(10),
    vendor_history_id integer,
    vendor_preference_level integer,
    original_contract_amount_original numeric(16,2),
    original_contract_amount numeric(16,2),
    registered_date_id int,
    oca_number character varying(20),
    number_solicitation integer,
    document_name character varying(60),
    original_term_begin_date_id int,
    original_term_end_date_id int,    
    brd_awd_no varchar,
    rfed_amount_original numeric(16,2),
    rfed_amount numeric(16,2),
    registered_fiscal_year smallint,
    registered_fiscal_year_id smallint, 
    registered_calendar_year smallint,
    registered_calendar_year_id smallint,
    effective_end_fiscal_year smallint,
    effective_end_fiscal_year_id smallint, 
    effective_end_calendar_year smallint,
    effective_end_calendar_year_id smallint,
    effective_begin_fiscal_year smallint,
    effective_begin_fiscal_year_id smallint,
    effective_begin_calendar_year smallint,
    effective_begin_calendar_year_id smallint,
    source_updated_fiscal_year smallint,
    source_updated_fiscal_year_id smallint, 
    source_updated_calendar_year smallint,
    source_updated_calendar_year_id smallint,
    contract_number varchar,
    original_agreement_id bigint,
    original_version_flag char(1),
    latest_flag char(1),
    privacy_flag char(1),
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;
 
 
DROP TABLE IF EXISTS history_agreement_accounting_line_edc; 
CREATE TABLE history_agreement_accounting_line_edc (
    agreement_accounting_line_id bigint   NOT NULL,
    agreement_id bigint,
    commodity_line_number integer,
    line_number integer,
    event_type_code char(4),
    description character varying(100),
    line_amount_original numeric(16,2),
    line_amount numeric(16,2),
    budget_fiscal_year smallint,
    fiscal_year smallint,
    fiscal_period character(2),
    fund_class_id smallint,
    agency_history_id smallint,
    department_history_id integer,
    expenditure_object_history_id integer,
    revenue_source_id int,
    location_code character varying(4),
    budget_code_id integer,
    reporting_code character varying(15),
    rfed_line_amount_original numeric(16,2),
    rfed_line_amount numeric(16,2),
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS history_master_agreement_edc;
CREATE TABLE history_master_agreement_edc
(
  master_agreement_id bigint NOT NULL ,
  document_code_id smallint,
  agency_history_id smallint,
  document_id character varying(20),
  document_version integer,
  tracking_number character varying(30),
  record_date_id int,
  budget_fiscal_year smallint,
  document_fiscal_year smallint,
  document_period character(2),
  description character varying(60),
  actual_amount_original numeric(16,2),
  actual_amount numeric(16,2),
  total_amount_original numeric(16,2),
  total_amount numeric(16,2),
  replacing_master_agreement_id bigint,
  replaced_by_master_agreement_id bigint,
  award_status_id smallint,
  procurement_id character varying(20),
  procurement_type_id smallint,
  effective_begin_date_id int,
  effective_end_date_id int,
  reason_modification character varying,
  source_created_date_id int,
  source_updated_date_id int,
  document_function_code character varying,
  award_method_id smallint,
  agreement_type_id smallint,
  award_category_id_1 smallint,
  award_category_id_2 smallint,
  award_category_id_3 smallint,
  award_category_id_4 smallint,
  award_category_id_5 smallint,
  number_responses integer,
  location_service character varying(255),
  location_zip character varying(10),
  borough_code character varying(10),
  block_code character varying(10),
  lot_code character varying(10),
  council_district_code character varying(10),
  vendor_history_id integer,
  vendor_preference_level integer,
  board_approved_award_no character varying(15),
  board_approved_award_date_id int,
  original_contract_amount_original numeric(20,2),
  original_contract_amount numeric(20,2),
  oca_number character varying(20),
  original_term_begin_date_id int,
  original_term_end_date_id int,
  registered_date_id int,
  maximum_amount_original numeric(20,2),
  maximum_amount numeric(20,2),
  maximum_spending_limit_original numeric(20,2),
  maximum_spending_limit numeric(20,2),
  award_level_code character(2),
  contract_class_code character varying(2),
  number_solicitation integer,
  document_name character varying(60),
  registered_fiscal_year smallint,
  registered_fiscal_year_id smallint,
  registered_calendar_year smallint,
  registered_calendar_year_id smallint,
  effective_end_fiscal_year smallint,
  effective_end_fiscal_year_id smallint,
  effective_end_calendar_year smallint,
  effective_end_calendar_year_id smallint,
  effective_begin_fiscal_year smallint,
  effective_begin_fiscal_year_id smallint,
  effective_begin_calendar_year smallint,
  effective_begin_calendar_year_id smallint,
  source_updated_fiscal_year smallint,
  source_updated_fiscal_year_id smallint,
  source_updated_calendar_year smallint,
  source_updated_calendar_year_id smallint,
  contract_number character varying,
  original_master_agreement_id bigint,
  num_associated_contracts smallint,
  original_version_flag character(1),
  latest_flag character(1),
  privacy_flag character(1),
  created_load_id integer,
  updated_load_id integer,
  created_date timestamp without time zone,
  updated_date timestamp without time zone
);


DROP TABLE IF EXISTS agreement_snapshot_edc;
 CREATE TABLE agreement_snapshot_edc
 (
   original_agreement_id bigint,
   document_version smallint,
   document_code_id smallint,
   agency_history_id smallint,
   agency_id smallint,
   agency_code character varying(20),
   agency_name character varying(100),
   agreement_id bigint,
   starting_year smallint,
   starting_year_id smallint,
   ending_year smallint,
   ending_year_id smallint,
   registered_year smallint,
   registered_year_id smallint,
   contract_number character varying,
   original_contract_amount numeric(16,2),
   maximum_contract_amount numeric(16,2),
   description character varying,
   vendor_history_id integer,
   vendor_id integer,
   vendor_code character varying(20),
   vendor_name character varying,
   dollar_difference numeric(16,2),
   percent_difference numeric(17,4),
   master_agreement_id bigint,
   master_contract_number character varying,
   agreement_type_id smallint,
   agreement_type_code character varying(2),
   agreement_type_name character varying,
   award_category_id smallint,
   award_category_code character varying(10),
   award_category_name character varying,
   award_method_id smallint,
   award_method_code character varying(10) ,
   award_method_name character varying,
   expenditure_object_codes character varying,
   expenditure_object_names character varying,
   industry_type_id smallint,
   industry_type_name character varying(50),
   award_size_id smallint,
   effective_begin_date date,
   effective_begin_date_id integer,
   effective_begin_year smallint,
   effective_begin_year_id smallint,
   effective_end_date date,
   effective_end_date_id integer,
   effective_end_year smallint,
   effective_end_year_id smallint,
   registered_date date,
   registered_date_id integer,
   brd_awd_no character varying,
   tracking_number character varying,
   rfed_amount numeric(16,2),
   master_agreement_yn character(1),  
   has_children character(1),
   original_version_flag character(1),
   latest_flag character(1),
   load_id integer,
   last_modified_date timestamp without time zone,
   job_id bigint
 ) ;
 
 
 DROP TABLE IF EXISTS agreement_snapshot_cy_edc;
 CREATE TABLE agreement_snapshot_cy_edc
 (
   original_agreement_id bigint,
   document_version smallint,
   document_code_id smallint,
   agency_history_id smallint,
   agency_id smallint,
   agency_code character varying(20),
   agency_name character varying(100),
   agreement_id bigint,
   starting_year smallint,
   starting_year_id smallint,
   ending_year smallint,
   ending_year_id smallint,
   registered_year smallint,
   registered_year_id smallint,
   contract_number character varying,
   original_contract_amount numeric(16,2),
   maximum_contract_amount numeric(16,2),
   description character varying,
   vendor_history_id integer,
   vendor_id integer,
   vendor_code character varying(20),
   vendor_name character varying,
   dollar_difference numeric(16,2),
   percent_difference numeric(17,4),
   master_agreement_id bigint,
   master_contract_number character varying,
   agreement_type_id smallint,
   agreement_type_code character varying(2),
   agreement_type_name character varying,
   award_category_id smallint,
   award_category_code character varying(10),
   award_category_name character varying,
   award_method_id smallint,
   award_method_code character varying(10) ,
   award_method_name character varying,
   expenditure_object_codes character varying,
   expenditure_object_names character varying,
   industry_type_id smallint,
   industry_type_name character varying(50),
   award_size_id smallint,
   effective_begin_date date,
   effective_begin_date_id integer,
   effective_begin_year smallint,
   effective_begin_year_id smallint,
   effective_end_date date,
   effective_end_date_id integer,
   effective_end_year smallint,
   effective_end_year_id smallint,
   registered_date date,
   registered_date_id integer,
   brd_awd_no character varying,
   tracking_number character varying,
   rfed_amount numeric(16,2),
   master_agreement_yn character(1),  
   has_children character(1),
   original_version_flag character(1),
   latest_flag character(1),
   load_id integer,
   last_modified_date timestamp without time zone,
   job_id bigint
 ) ;
 
 
 DROP TABLE IF EXISTS agreement_snapshot_expanded_edc;
 CREATE TABLE agreement_snapshot_expanded_edc(
	original_agreement_id bigint,
	agreement_id bigint,
	fiscal_year smallint,
	description varchar,
	contract_number varchar,
	vendor_id int,
	agency_id smallint,
	industry_type_id smallint,
    award_size_id smallint,
	original_contract_amount numeric(16,2) ,
	maximum_contract_amount numeric(16,2),
	rfed_amount numeric(16,2),
	starting_year smallint,	
	ending_year smallint,
	dollar_difference numeric(16,2), 
	percent_difference numeric(17,4),
	award_method_id smallint,
	document_code_id smallint,
	master_agreement_id bigint,
	master_agreement_yn character(1),
	status_flag char(1)
	);	

DROP TABLE IF EXISTS agreement_snapshot_expanded_cy_edc;
CREATE TABLE agreement_snapshot_expanded_cy_edc(
	original_agreement_id bigint,
	agreement_id bigint,
	fiscal_year smallint,
	description varchar,
	contract_number varchar,
	vendor_id int,
	agency_id smallint,
	industry_type_id smallint,
    award_size_id smallint,
	original_contract_amount numeric(16,2) ,
	maximum_contract_amount numeric(16,2),
	rfed_amount numeric(16,2),
	starting_year smallint,	
	ending_year smallint,
	dollar_difference numeric(16,2), 
	percent_difference numeric(17,4),
	award_method_id smallint,
	document_code_id smallint,
	master_agreement_id bigint,
	master_agreement_yn character(1),
	status_flag char(1)
	);	


DROP TABLE IF EXISTS address_edc;
CREATE TABLE address_edc (
  address_id int PRIMARY KEY ,
  address_line_1 varchar(75) ,
  address_line_2 varchar(75) ,
  city varchar(60) ,
  state varchar(25) ,
  zip varchar(25) ,
  country varchar(25) 
) ;

DROP TABLE IF EXISTS vendor_edc;
CREATE TABLE vendor_edc (
    vendor_id integer PRIMARY KEY NOT NULL,
    vendor_customer_code character varying(25),
    legal_name character varying(60),
    alias_name character varying(60),
    miscellaneous_vendor_flag bit(1),
    vendor_sub_code integer ,
    display_flag CHAR(1) DEFAULT 'Y',
    created_load_id integer,
    updated_load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS vendor_history_edc;
CREATE TABLE vendor_history_edc (
    vendor_history_id integer PRIMARY KEY  NOT NULL,
    vendor_id integer,   
    legal_name character varying(60),
    alias_name character varying(60),
    miscellaneous_vendor_flag bit(1),
    vendor_sub_code integer ,
    load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;


DROP TABLE IF EXISTS vendor_address_edc;
CREATE TABLE vendor_address_edc (
    vendor_address_id bigint PRIMARY KEY  NOT NULL,
    vendor_history_id integer,
    address_id integer,
    address_type_id smallint,
    effective_begin_date_id int,
    effective_end_date_id int,
    load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;

DROP TABLE IF EXISTS vendor_business_type_edc;
CREATE TABLE vendor_business_type_edc (
    vendor_business_type_id bigint PRIMARY KEY  NOT NULL,
    vendor_history_id integer,
    business_type_id smallint,
    status smallint,
    minority_type_id smallint,
    load_id integer,
    created_date timestamp without time zone,
    updated_date timestamp without time zone
) ;

DROP TABLE IF EXISTS pending_contracts_edc;

CREATE TABLE pending_contracts_edc
(
  document_code_id smallint,
  document_agency_id smallint,
  document_id character varying,
  parent_document_code_id smallint,
  parent_document_agency_id smallint,
  parent_document_id character varying,
  encumbrance_amount_original numeric(15,2),
  encumbrance_amount numeric(15,2),
  original_maximum_amount_original numeric(15,2),
  original_maximum_amount numeric(15,2),
  revised_maximum_amount_original numeric(15,2),
  revised_maximum_amount numeric(15,2),
  registered_contract_max_amount numeric(15,2),
  vendor_legal_name character varying(80),
  vendor_customer_code character varying(20),
  vendor_id integer,
  description character varying(78),
  submitting_agency_id smallint,
  oaisis_submitting_agency_desc character varying(50),
  submitting_agency_code character varying(4),
  awarding_agency_id smallint,
  oaisis_awarding_agency_desc character varying(50),
  awarding_agency_code character varying(4),
  contract_type_name character varying(40),
  cont_type_code character varying(2),
  award_method_name character varying(50),
  award_method_code character varying(3),
  award_method_id smallint,
  start_date date,
  end_date date,
  revised_start_date date,
  revised_end_date date,
  cif_received_date date,
  cif_fiscal_year smallint,
  cif_fiscal_year_id smallint,
  tracking_number character varying(30),
  board_award_number character varying(15),
  oca_number character varying(10),
  version_number character varying(5),
  fms_contract_number character varying,
  contract_number character varying,
  fms_parent_contract_number character varying,
  submitting_agency_name character varying,
  submitting_agency_short_name character varying,
  awarding_agency_name character varying,
  awarding_agency_short_name character varying,
  start_date_id integer,
  end_date_id integer,
  revised_start_date_id integer,
  revised_end_date_id integer,
  cif_received_date_id integer,
  document_agency_code character varying,
  document_agency_name character varying,
  document_agency_short_name character varying,
  funding_agency_id smallint,
  funding_agency_code character varying,
  funding_agency_name character varying,
  funding_agency_short_name character varying,
  original_agreement_id bigint,
  original_master_agreement_id bigint,
  dollar_difference numeric(16,2),
  percent_difference numeric(17,4),
  original_or_modified character varying,
  original_or_modified_desc character varying,
  award_size_id smallint,
  award_category_id smallint,
  industry_type_id smallint,
  document_version smallint,
  latest_flag character(1)
);

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- creating indexes


  CREATE INDEX idx_oge_contract_id_oge_contract_previous_load   ON  oge_contract_previous_load(oge_contract_id) ;
  CREATE INDEX idx_oge_contract_id_oge_contract_history   ON  oge_contract_history(oge_contract_id) ;
  CREATE INDEX idx_fms_contract_number_oge_contract_vendor_level   ON  oge_contract_vendor_level(fms_contract_number) ;
  CREATE INDEX idx_fms_contract_number_oge_contract_contract_level   ON  oge_contract_contract_level(fms_contract_number) ;
  
  
  CREATE INDEX idx_disbursement_line_item_id_disb_line_item_details_edc   ON  disbursement_line_item_details_edc(disbursement_line_item_id) ;
  
  CREATE INDEX idx_agreement_id_history_agreement_acc_line_edc   ON  history_agreement_accounting_line_edc(agreement_id) ;
  CREATE INDEX idx_master_agreement_id_history_master_agreement_edc   ON  history_master_agreement_edc(master_agreement_id) ;
  
  CREATE INDEX idx_original_agreement_id_agreement_snapshot_edc   ON  agreement_snapshot_edc(original_agreement_id) ;
  CREATE INDEX idx_original_agreement_id_agreement_snapshot_cy_edc   ON  agreement_snapshot_cy_edc(original_agreement_id) ;
  CREATE INDEX idx_original_agreement_id_ag_snapshot_expanded_edc   ON  agreement_snapshot_expanded_edc(original_agreement_id) ;
  CREATE INDEX idx_original_agreement_id_ag_snap_expanded_cy_edc   ON  agreement_snapshot_expanded_cy_edc(original_agreement_id) ;
  
  