<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/*************************************************************************************/
/* Widget Hooks                                                                      */
/*************************************************************************************/

function widget_phpparser_widget_metadata() {
	return array(
    'phpparser' => array(
      'name' => t('PHPParser'),
      'module' => 'widget_phpparser',
      'description' => t("This widget type implements PHP parsing.")
	)
	);
}


function widget_phpparser_widget_prepare(&$node) {

    if (isset($node->widgetConfig->prepareConfig)) {
        eval($node->widgetConfig->prepareConfig);
    }

}

function widget_phpparser_widget_validate(&$node) {

}

function widget_phpparser_widget_data(&$node) {

}

function widget_phpparser_widget_view(&$node) {
    $code = $node->widgetConfig->phpcode;
    if(isset($code)){
        return eval($code);
    }
    
    $customDataHandlerClass = $node->widgetConfig->customDataHandlerClass;
    if(isset($customDataHandlerClass)){
       $class =  new $customDataHandlerClass();
       $class->getData($node ) ;       
    }

    $template = $node->widgetConfig->template;
    return theme($template, array('node'=> $node));
}
