<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



function log_menu() {
  $items = array();

  $items['admin/settings/log'] = array(
    'title' => t('Log4Drupal'),
    'description' => t('Administer log4drupal, a file-based logging framework.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('log_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * We want this module to be loaded during the boostrap phase, so add an empty
 * hook_boot method.
 *
 */
function log_boot() {
  log_notice("RUNNING BOOT FOR LOG MODULE");
}

function log_admin_settings() {

  $form['log_loglevel'] = array(
    '#type' => 'radios',
    '#title' => t('Log priority level'),
    '#default_value' => variable_get('log_loglevel', Log::MAX(PEAR_LOG_DEBUG)),
    '#options' => array (
      Log::MAX(PEAR_LOG_EMERG) => t('emergency'),
      Log::MAX(PEAR_LOG_ALERT) => t('alert'),
      Log::MAX(PEAR_LOG_CRIT) => t('critical'),
      Log::MAX(PEAR_LOG_ERR) => t('error'),
      Log::MAX(PEAR_LOG_WARNING) => t('warning'),
      Log::MAX(PEAR_LOG_NOTICE) => t('notice'),
      Log::MAX(PEAR_LOG_INFO) => t('info'),
      Log::MAX(PEAR_LOG_DEBUG) => t('debug')
      ),
    '#description' => t('All messages for specified level and above will appear in log file')
  );

  $form['log_stacklevel'] = array(
    '#type' => 'radios',
    '#title' => t('Stack trace priority level'),
    '#default_value' => variable_get('log_stacklevel', Log::MAX(PEAR_LOG_ERR)),
    '#options' => array (
      Log::MAX(PEAR_LOG_EMERG) => t('emergency'),
      Log::MAX(PEAR_LOG_ALERT) => t('alert'),
      Log::MAX(PEAR_LOG_CRIT) => t('critical'),
      Log::MAX(PEAR_LOG_ERR) => t('error'),
      Log::MAX(PEAR_LOG_WARNING) => t('warning'),
      Log::MAX(PEAR_LOG_NOTICE) => t('notice'),
      Log::MAX(PEAR_LOG_INFO) => t('info'),
      Log::MAX(PEAR_LOG_DEBUG) => t('debug')
      ),
    '#description' => t('All messages for specified level and above will include a stack trace in the log file')
  );

  $form['log_precision'] = array(
    '#type' => 'radios',
    '#title' => t('Filename precision'),
    '#default_value' => variable_get('log_precision', 2),
    '#options' => array (
      t('Absolute path'),
      t('Path relative to Drupal root'),
      t('Filename only'),
    ),
    '#description' => t('For log messages, how long should the filename be?  Stack traces always include absolute paths.')
  );

  $form['log_logfile'] = array(
    '#type' => 'textfield',
    '#title' => t('Log file location'),
    '#default_value' => variable_get('log_logfile', '/var/log/drupal/drupal.log'),
    '#description' => t('Specify the absolute path for the file you would like to log to.'),
    '#required' => TRUE
  );



  return system_settings_form($form);
}

function log_help($section='')
{
  $output = '';

  switch ($section)
  {
    case "admin/help#log":
      $output = '<p>'.  t("Blah blah two"). '</p>';
      break;
  }

  return $output;
}

/**
 * Generate a logger.
 *
 * @return object
 */
function _log_get_logger()
{
  static $logger;

  if ( isset($logger))
  return $logger;

  $conf = array(
      'lineFormat' => '[%1$s] [%3$s] %4$s',
      'timeFormat' => '%b %d %H:%M:%S'
      );

      $logger = Log::singleton(
        'file',
        variable_get('log_logfile', '/var/log/drupal/drupal.log'),
        NULL,
        $conf
        );

      $logger->setMask(variable_get('log_loglevel', Log::MAX(PEAR_LOG_DEBUG)));
      return $logger;
}

/**
 * Actually write the log message to the log file
 *
 * @param $message  The message to be written to the log file
 * @param $level The log level of the message
 */
function _log_write_log_message($message, $level) {

  $stacklevel = variable_get('log_stacklevel', Log::MAX(PEAR_LOG_ERR));

  if($stacklevel &  Log::MASK($level)) {
    $include_stacktrace = TRUE;
  } else {
	$include_stacktrace = FALSE;
  }

  $trace = debug_backtrace();

  $log_message =  _log_get_top($trace). _log_url() . $message;

  if($include_stacktrace) {
   $log_message .= _log_get_stacktrace($trace);
  }

  _log_get_logger()->log($log_message, $level);
}

/**
 * @return string
 */
function _log_url() {
  if (empty($_SERVER['HTTP_HOST'])) {
    return '';
  }
  $url = ($_SERVER['HTTPS'] ?? false) ? 'https' : 'http';
  $uri = request_uri();
  $url .= "://{$_SERVER['HTTP_HOST']}{$uri}";

  return "[$url] ";
}

/**
 * Return a simple string containing the file name and line number from which
 * the log statement was generated.
 *
 * @param $trace  The output generated by debug_backtrace
 * @return string
 */
function _log_get_top($trace) {

  // Special case messages originating from our implementation of hook_watchdog
  if($trace[1]['function'] == 'log_watchdog') {
    $file = $trace[4]['file'];
    $line = $trace[4]['line'];
  }
  else {
    // The very top of the trace (the 0th element) always comes from
    // this module.  This is not very useful information for the end user
    $file = $trace[1]['file'];
    $line = $trace[1]['line'];
  }

  switch(variable_get('log_precision', 0)) {
    case 1: $file = substr($file, strlen($_SERVER['DOCUMENT_ROOT'] . $GLOBALS['base_path'] )); break;
    case 2: $file = pathinfo($file, PATHINFO_BASENAME ); break;
  }
  return "[$file:$line] ";
}

/**
 * Return a "Java style" full stacktrace
 *
 * @param $trace
 * @return string
 */
function _log_get_stacktrace($trace) {
  $output = '';

  // Special case messages originating from our implementation of hook_watchdog
  if($trace[1]['function'] == 'log_watchdog') {
    $start_trace = 4;
  }
  else {
    $start_trace = 1;
  }

  foreach($trace as $i => $step) {
    if(array_key_exists('file', $step)) {
      // The top of the trace always comes from this module.
      // This is not very useful information for the end user so we skip it.
      if($i >= $start_trace ) {
        $output .= PHP_EOL . "  at " . $step['file'] . ':' . $step['line'];
      }
    }
  }

  return $output;
}

function _log_get_message($args) {
	if(is_string($args[0])) {
		$message = $args[0];
	} else {
		$message = var_export($args[0], true);
	}

  foreach ($args as $count => $arg){
    if($count > 0) {
		if(is_string($arg)) {
			$message .=  " " . $arg;
		} else {
			$message .=  PHP_EOL . var_export($arg, true) . PHP_EOL;
		}
    }
  }
  return $message;
}

function log_debug($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_DEBUG)) {
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_DEBUG);
  }
}

function log_info($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_INFO)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_INFO);
  }
}

function log_notice($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_NOTICE)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_NOTICE);
  }
}

function log_warn($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_WARNING)) {
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_WARNING);
  }
}

function log_error($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_ERR)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_ERR);
  }
}

function log_critical($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_CRIT)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_CRIT);
  }
}

function log_alert($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_ALERT)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_ALERT);
  }
}

function log_emergency($message) {

  if(_log_get_logger()->getMask() &  Log::MASK(PEAR_LOG_EMERG)){
    $message = _log_get_message(func_get_args());
    _log_write_log_message($message, PEAR_LOG_EMERG);
  }
}

function log_watchdog($entry) {
  $message = strip_tags(is_null($entry['variables']) ? $entry['message'] : strtr($entry['message'], $entry['variables']));
  $severity = $entry['severity'];
  _log_write_log_message($message, $severity);
}


require_once 'Log-1.12.x/Log.php';
require_once 'Log-1.12.x/Log/file.php';
