<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (C) 2012, 2013 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


module_load_include('inc', 'checkbook_advanced_search', 'includes/checkbook_advanced_search');
module_load_include('inc', 'checkbook_advanced_search_autocomplete', 'includes/checkbook_advanced_search_autocomplete_functions');

/**
 * Implements of hook_menu().
 */
function checkbook_advanced_search_menu()
{
    $items['advanced-search'] = array(
        'title' => 'Checkbook Advanced Search',
        'page callback' => 'checkbook_advanced_search_display',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['advanced-search/autocomplete'] = array(
        'page callback' => '_checkbook_advanced_search_autocomplete_get_agencyname_and_id',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function checkbook_advanced_search_display()
{
    return drupal_get_form('checkbook_advanced_search_form');
}

/**
 * Implements hook_form().
 */
function checkbook_advanced_search_form($form, $form_state)
{
    $agencies = _checkbook_advanced_search_get_agencyname_and_id();
    $agency_attributes = _checkbook_advanced_search_get_agency_attributes();
    $fund_class = _checkbook_advanced_search_get_fund_class_and_id();
    $year_range = "'-" . (date("Y") - 1900) . ":+" . (2500 - date("Y")) . "'";
    $revenue_fys = array(0 => "All Fiscal Years") + _checkbook_advanced_search_get_year('revenue');
    $form['opening_div'] = array(
        '#type' => 'markup',
        '#markup' => '<div class = "advanced-search-accordion">',
    );

    //<editor-fold desc="Budget">

    $form['budget']['budget_agencies'] = array(
        '#type' => 'select',
        '#title' => t('Agency'),
        '#prefix' => '<h3><a href="#">Budget</a></h3><div id="budget-advanced-search"><div class="column column-left">',
        '#default_value' => t('Citywide(All Agencies)'),
        '#options' => $agencies,
        '#option_attributes' => $agency_attributes,
        //advanced-search-disable-accordion
    );
    $form['budget']['budget_department'] = array(
        '#type' => 'select',
        '#title' => t('Department'),
        '#default_value' => t('Select Department'),
        '#options' => array('Select Department'),
        '#disabled' => TRUE,
    );
    $form['budget']['budget_expense_category'] = array(
        '#type' => 'select',
        '#title' => t('Expense Category'),
        '#default_value' => t('Select Expense Category'),
        '#options' => array("Select Expense Category"),
        '#disabled' => TRUE,
    );

    $form['budget']['budget_budget_code'] = array(
        '#type' => 'textfield',
        '#title' => t('Budget Code'),
        '#size' => 30,
        '#maxlength' => 100
    );

    $form['budget']['budget_fiscal_year'] = array(
        '#type' => 'select',
        '#title' => t('Year'),
        '#default_value' => _getCurrentYearID(),
        '#options' => _checkbook_advanced_search_get_year('budget'),
        '#attributes' => array('default_selected_value' => _getCurrentYearID())
    );

    $form['budget']['budget_adopted_budget_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_adopted_budget datarange"><label>Adopted</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-adopted">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_adopted_budget_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div></div>',
    );
    $form['budget']['budget_current_modified_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="column column-right"><div class="datafield budget_current_modified datarange"><label>Modified</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-modified">',
        '#suffix' => '<span class="advanced-search-to">to </span>'
    );
    $form['budget']['budget_current_modified_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );


    $form['budget']['budget_pre_encumbered_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_pre_encumbered datarange"><label>Pre Encumbered</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-pre-encumbered">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_pre_encumbered_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );
    $form['budget']['budget_encumbered_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_encumbered datarange"><label>Encumbered</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-encumbered">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_encumbered_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );
    $form['budget']['budget_accrued_expense_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_accrued_expense datarange"><label>Accrued Expense</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-accrued-expense">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_accrued_expense_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );
    $form['budget']['budget_cash_expense_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_cash_expense datarange"><label>Cash Payments</label></label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-expense">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_cash_expense_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );
    $form['budget']['budget_post_adjustments_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield budget_post_adjustments datarange"><label>Post Adjustments</label><div class="ranges"><div class="form-item form-type-textfield form-item-budget-post-adjustments">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['budget']['budget_post_adjustments_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div></div>',
    );

    $form['budget']['budget_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
        '#name' => 'budget_submit',
        '#prefix' => t('<div class="budget-submit">'),
    );
    $form['budget']['budget_clear'] = array(
        '#suffix' => '</div></div>',
        '#type' => 'submit',
        '#value' => t('Clear All'),
    );

    //</editor-fold>

    //<editor-fold desc="Revenue">

    $form['revenue']['revenue_budget_fiscal_year'] = array(
        '#prefix' => '<h3><a href="#">Revenue</a></h3><div id="revenue-advanced-search"><div class="column column-left">',
        '#type' => 'select',
        '#title' => t('Budget FY:'),
        '#options' => _checkbook_advanced_search_get_year('revenue'),
        '#attributes' => array('default_selected_value' => _getCurrentYearID()),
        '#default_value' => _getCurrentYearID(),
    );
    $form['revenue']['revenue_agencies'] = array(
        '#type' => 'select',
        '#title' => t('Agency:'),
        '#options' => $agencies,
        '#option_attributes' => $agency_attributes,
    );
    $form['revenue']['revenue_revenue_category'] = array(
        '#type' => 'select',
        '#title' => t('Revenue Category:'),
        '#options' => _checkbook_advanced_search_get_revenue_category_and_id(),
    );
    $form['revenue']['revenue_revenue_source'] = array(
        '#type' => 'textfield',
        '#title' => t('Revenue Source:'),
        '#size' => 30,
        '#maxlength' => 100
    );
    $form['revenue']['revenue_revenue_source_exact'] = array(
        '#type' => 'hidden'
    );
    $form['revenue']['revenue_adopted_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield revenue_adopted datarange"><label>Adopted:</label><div class="ranges"><div class="form-item form-type textfield form-item-revenue-adopted">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['revenue']['revenue_adopted_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div>',
    );


    $form['revenue']['revenue_recognized_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield revenue_recognized datarange"><label>Recognized:</label><div class="ranges"><div class="form-item form-type textfield form-item-revenue-recognized">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['revenue']['revenue_recognized_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div></div>',
    );

    $form['revenue']['revenue_fiscal_year'] = array(
        '#prefix' => '<div class="column column-right">',
        '#type' => 'select',
        '#title' => t('Fiscal Year:'),
        '#options' => $revenue_fys,
    );
    $form['revenue']['revenue_funding_source'] = array(
        '#type' => 'select',
        '#title' => t('Funding Class'),
        '#options' => _checkbook_advanced_search_get_funding_source_and_id(),
    );
    $form['revenue']['revenue_revenue_class'] = array(
        '#type' => 'textfield',
        '#title' => t('Revenue Class:'),
        '#size' => 30,
        '#maxlength' => 100
    );
    $form['revenue']['revenue_revenue_class_exact'] = array(
        '#type' => 'hidden'
    );

    $form['revenue']['revenue_fund_class'] = array(
        '#type' => 'select',
        '#title' => t('Fund Class:'),
        '#options' => $fund_class,

    );
    $form['revenue']['revenue_modified_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="datafield revenue_modified datarange"><label>Modified:</label><div class="ranges"><div class="form-item form-type textfield form-item-revenue-modified">',
        '#suffix' => '<span class="advanced-search-to">to </span>',
    );
    $form['revenue']['revenue_modified_to'] = array(
        '#type' => 'textfield',
        '#title' => t(''),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div></div></div>',
    );
    $form['revenue']['revenue_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
        '#name' => 'revenue_submit',
        '#prefix' => t('<div class="revenue-submit">'),
    );
    $form['revenue']['revenue_clear'] = array(
        '#suffix' => '</div></div>',
        '#type' => 'submit',
        '#value' => t('Clear All'),
    );

    //</editor-fold>

    //<editor-fold desc="Spending">

    $form = _checkbook_advanced_search_get_form($form, Domain::Spending, $agencies, $agency_attributes, $year_range);

    //</editor-fold>

    //<editor-fold desc="Contracts">

    $form = _checkbook_advanced_search_get_form($form, Domain::Contracts, $agencies, $agency_attributes, $year_range);

    //</editor-fold>

    //<editor-fold desc="Payroll">

    $form['payroll']['payroll_employee_name'] = array(
        '#prefix' => '<h3><a href="#">Payroll</a></h3><div id="payroll-advanced-search"><div class="column column-left">',
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#size' => 30,
        '#maxlength' => 100,
    );
    $form['payroll']['payroll_agencies'] = array(
        '#type' => 'select',
        '#title' => t('Agency'),
        '#default_value' => t('Citywide(All Agencies)'),
        '#options' => $agencies,
        '#option_attributes' => $agency_attributes,
    );
    $form['payroll']['payroll_other_payments_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="form-item form-item-payroll-other-payments"><label>Other Payments</label><div class="ranges">',
    );
    $form['payroll']['payroll_other_payments_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );
    $form['payroll']['payroll_gross_pay_amount_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="form-item form-item-payroll-pay-amount"><label>Gross Pay</label><div class="ranges">',
    );
    $form['payroll']['payroll_gross_pay_amount_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );
    $form['payroll']['payroll_total_gross_pay_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="form-item form-item-payroll-total-gross-pay"><label>Gross Pay YTD</label><div class="ranges">',
    );
    $form['payroll']['payroll_total_gross_pay_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );
    $form['payroll']['payroll_amount_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="form-item form-item-payroll-amount"><label>Amount</label><div class="ranges">',
    );
    $form['payroll']['payroll_amount_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );
    $form['payroll']['payroll_amount_type'] = array(
        '#type' => 'radios',
        '#default_value' => 0,
        '#options' => array(0 => t('All'), 1 => t('Annual'), 2 => t('Rate')),
        '#suffix' => '</div>',
    );
    $form['payroll']['payroll_base_salary_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="column column-right"><div class="form-item form-item-payroll-base-salary"><label>Base Pay</label><div class="ranges">',
    );
    $form['payroll']['payroll_base_salary_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );

    $form['payroll']['payroll_overtime_amount_from'] = array(
        '#type' => 'textfield',
        '#size' => 30,
        '#maxlength' => 32,
        '#prefix' => '<div class="form-item form-item-payroll-overtime-amount"><label>Overtime Payments</label><div class="ranges">',
    );
    $form['payroll']['payroll_overtime_amount_to'] = array(
        '#type' => 'textfield',
        '#title' => t('TO'),
        '#size' => 30,
        '#maxlength' => 32,
        '#suffix' => '</div></div>',
    );
    $form['payroll']['payroll_pay_frequency'] = array(
        '#type' => 'select',
        '#title' => t('Pay Frequency'),
        '#default_value' => t('Select Pay Frequency'),
        '#options' => _checkbook_advanced_search_get_payroll_frequency(),
    );
    $form['payroll']['payroll_year'] = array(
        '#type' => 'select',
        '#title' => t('Year'),
        '#default_value' => 'fy~' . _getCurrentYearID(),
        '#options' => _checkbook_advanced_search_get_year('payroll'),
        '#attributes' => array('default_selected_value' => 'fy~' . _getCurrentYearID())
    );
    $form['payroll']['payroll_pay_date_from'] = array(
        '#type' => 'date_popup',
        '#date_format' => 'Y-m-d',
        '#date_year_range' => '-3:+3',
        '#prefix' => '<div class="form-item form-item-payroll-pay-date"><label>Pay Date</label><div class="ranges">',
    );
    $form['payroll']['payroll_pay_date_to'] = array(
        '#type' => 'date_popup',
        '#date_format' => 'Y-m-d',
        '#date_year_range' => '-3:+3',
        '#title' => t('TO'),
        '#description' => '',
        '#suffix' => '</div></div></div>',
    );
    $form['payroll']['payroll_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
        '#name' => 'payroll_submit',
        '#prefix' => t('<div class="payroll-submit">'),
    );
    $form['payroll']['payroll_clear'] = array(
        '#suffix' => '</div>',
        '#type' => 'submit',
        '#value' => t('Clear All'),
    );

    //</editor-fold>

    $form['closing_div'] = array(
        '#type' => 'markup',
        '#markup' => '</div></div>',
    );
    $form['#attached'] = array(
        'library' => array(
            array('system', 'ui.accordion', FALSE),
            array('system', 'ui.autocomplete', FALSE),
        ),
        'js' => array(
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_clear_button.js',
            ),
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_spending.js',
            ),
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_budget.js',
            ),
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_revenue.js',
            ),
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_payroll.js',
            ),
            array(
                'type' => 'file',
                'data' => drupal_get_path('module', 'checkbook_advanced_search') . '/js/checkbook_advanced_search_contracts.js',
            ),
        ),
    );

    return $form;
}

function _get_all_field_definitions($domain,$data_source,$agencies,$agency_attributes,$year_range)
{
    switch($data_source)
    {
        case DataSource::CitywideAgency:
            break;
        case DataSource::OtherGovernmentEntities:
            $agencies = _checkbook_advanced_search_get_agencyname_and_id_by_data_source($data_source);
            $agency_attributes = _checkbook_advanced_search_get_agency_attributes_by_data_source($data_source);
            break;
    }
    $expense_attributes = _checkbook_advanced_search_get_expensetype_and_id($data_source);
    $year_attribute = _checkbook_advanced_search_get_year($domain,$data_source);
    $award_method =  _checkbook_advanced_search_get_contract_award_method_and_id($data_source);
    $award_method_attributes = _checkbook_advanced_search_get_contract_award_method_attributes($data_source);

    //Department
    $field_array[FieldDef::Department] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::Department
    );

    //ExpenseCategory
    $field_array[FieldDef::ExpenseCategory] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::ExpenseCategory
    );

    //SpendingCategory
    $field_array[FieldDef::SpendingCategory] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::SpendingCategory,
        'attributes' => array(
            'options' => $expense_attributes
        ));


    //PayeeName
    $field_array[FieldDef::PayeeName] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::PayeeName,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100
        ));

    //CheckAmount
    $field_array[FieldDef::CheckAmount] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::CheckAmount,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 32
        ));

    //DocumentId
    $field_array[FieldDef::DocumentId] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::DocumentId,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('Document ID')
        ));

    //CapitalProject
    $field_array[FieldDef::CapitalProject] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::CapitalProject,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100
        ));

    //DateFilter
    $field_array[FieldDef::DateFilter] = array(
        'field_type' => FieldType::DateFilter,
        'field_name' => FieldDef::DateFilter
        );

    //SpendingSubmit
    $field_array[FieldDef::SpendingSubmit] = array(
        'field_type' => FieldType::SubmitField,
        'field_name' => FieldDef::SpendingSubmit
    );

    //Data Source Filter
    $field_array[FieldDef::DataSourceFilter] = array(
        'field_type' => FieldType::RadioButtons,
        'field_name' => FieldDef::DataSourceFilter,
        'attributes' => array(
            'options' => array('Citywide Agencies','Other Government Entities')
        ));

    //Status
    $field_array[FieldDef::Status] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::Status,
        'attributes' => array(
            'options' => array('A' => 'Active', 'P' => 'Pending', 'R' => 'Registered'),
            'default_value' => ''
        ));

    //Vendor
    $field_array[FieldDef::Vendor] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::Vendor,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('Vendor')
        ));

    //Contract Type
    $field_array[FieldDef::ContractType] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::ContractType,
        'attributes' => array(
            'options' => $agencies,
            'option_attributes' => $agency_attributes,
            'title' => t('Contract Type')
        ));

    //Contract Id
    $field_array[FieldDef::ContractId] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::ContractId,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('Contract ID')
        ));

    //PIN
    $field_array[FieldDef::PIN] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::PIN,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('PIN')
        ));

    //Current Amount
    $field_array[FieldDef::CurrentContractAmount] = array(
        'field_type' => FieldType::RangeField,
        'field_name' => FieldDef::CurrentContractAmount,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 32,
            'title' => t('Current Amount')
        ));

    //End Date
    $field_array[FieldDef::EndDate] = array(
        'field_type' => FieldType::RangeDateField,
        'field_name' => FieldDef::EndDate,
        'attributes' => array(
            'date_year_range' => $year_range
        ));

    //Registration Date
    $field_array[FieldDef::RegistrationDate] = array(
        'field_type' => FieldType::RangeDateField,
        'field_name' => FieldDef::RegistrationDate,
        'attributes' => array(
            'date_year_range' => $year_range
        ));

    //Category
    $field_array[FieldDef::Category] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::Category,
        'attributes' => array(
            'options' => array('expense' => 'Expense', 'revenue' => 'Revenue')
        ));

    //Contract Type
    $field_array[FieldDef::Purpose] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::Purpose,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100
        ));


    //Agency
    $field_array[FieldDef::Agency] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::Agency,
        'attributes' => array(
            'options' => $agency_attributes
        ));

    //APT PIN
    $field_array[FieldDef::AptPIN] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::AptPIN,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('APT PIN')
        ));

    //Award Method
    $field_array[FieldDef::AwardMethod] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::AwardMethod,
        'attributes' => array(
            'options' => $award_method,
            'option_attributes' => $award_method_attributes
        ));

    //Start Date
    $field_array[FieldDef::StartDate] = array(
        'field_type' => FieldType::RangeDateField,
        'field_name' => FieldDef::StartDate,
        'attributes' => array(
            'date_year_range' => $year_range
        ));

    //Received Date
    $field_array[FieldDef::ReceivedDate] = array(
        'field_type' => FieldType::RangeDateField,
        'field_name' => FieldDef::ReceivedDate,
        'attributes' => array(
            'date_year_range' => $year_range
        ));

    //Year
    $field_array[FieldDef::Year] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::Year,
        'attributes' => array(
            'options' => $year_attribute
        ));

    //Contracts Submit
    $field_array[FieldDef::ContractSubmit] = array(
    'field_type' => FieldType::SubmitField,
    'field_name' => FieldDef::ContractSubmit
    );

    //Entity Contract Number
    $field_array[FieldDef::EntityContractNumber] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::EntityContractNumber,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100,
            'title' => t('Entity Contract #')
        ));

    //Commodity Line
    $field_array[FieldDef::CommodityLine] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::CommodityLine,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100
        ));

    //Budget Name
    $field_array[FieldDef::BudgetName] = array(
        'field_type' => FieldType::TextField,
        'field_name' => FieldDef::BudgetName,
        'attributes' => array(
            'size' => 30,
            'maxlength' => 100
        ));

    //Other Government Entities
    $field_array[FieldDef::OtherGovernmentEntities] = array(
        'field_type' => FieldType::DropDown,
        'field_name' => FieldDef::OtherGovernmentEntities,
        'attributes' => array(
            'options' => $agency_attributes
        ));

    return $field_array;

}

function _get_form_field_configurations($domain)
{
    switch($domain)
    {
        case Domain::Spending:
            $fields =  array(
                DataSource::CitywideAgency => array(
                    array('field_name'=> FieldDef::DataSourceFilter,'column' => Column::None),
                    array('field_name'=> FieldDef::Agency,'column' => Column::Left),
                    array('field_name'=> FieldDef::Department,'column' => Column::Left,'disabled' => TRUE),
                    array('field_name'=> FieldDef::ExpenseCategory,'column' => Column::Left,'disabled' => TRUE),
                    array('field_name'=> FieldDef::SpendingCategory,'column' => Column::Left),
                    array('field_name'=> FieldDef::PayeeName,'column' => Column::Left),
                    array('field_name'=> FieldDef::CheckAmount,'column' => Column::Right),
                    array('field_name'=> FieldDef::ContractId,'column' => Column::Right),
                    array('field_name'=> FieldDef::DocumentId,'column' => Column::Right),
                    array('field_name'=> FieldDef::CapitalProject,'column' => Column::Right),
                    array('field_name'=> FieldDef::DateFilter,'column' => Column::Right),
                    array('field_name'=> FieldDef::SpendingSubmit,'column' => Column::None),
                ),
                DataSource::OtherGovernmentEntities => array(
                    array('field_name'=> FieldDef::OtherGovernmentEntities,'column' => Column::Left),
                    array('field_name'=> FieldDef::Department,'column' => Column::Left,'disabled' => TRUE),
                    array('field_name'=> FieldDef::ExpenseCategory,'column' => Column::Left,'disabled' => TRUE),
                    array('field_name'=> FieldDef::SpendingCategory,'column' => Column::Left),
                    array('field_name'=> FieldDef::PayeeName,'column' => Column::Left),
                    array('field_name'=> FieldDef::CheckAmount,'column' => Column::Left),
                    array('field_name'=> FieldDef::ContractId,'column' => Column::Right),
                    array('field_name'=> FieldDef::EntityContractNumber,'column' => Column::Right),
                    array('field_name'=> FieldDef::DocumentId,'column' => Column::Right),
                    array('field_name'=> FieldDef::CapitalProject,'column' => Column::Right),
                    array('field_name'=> FieldDef::CommodityLine,'column' => Column::Right),
                    array('field_name'=> FieldDef::BudgetName,'column' => Column::Right),
                    array('field_name'=> FieldDef::DateFilter,'column' => Column::Right),
                    array('field_name'=> FieldDef::SpendingSubmit,'column' => Column::None),
                )
            );
            break;

        case Domain::Contracts:
            $fields =  array(
                DataSource::CitywideAgency => array(
                    array('field_name'=> FieldDef::DataSourceFilter,'column' => Column::None),
                    array('field_name'=> FieldDef::Status,'column' => Column::Left),
                    array('field_name'=> FieldDef::Vendor,'column' => Column::Left),
                    array('field_name'=> FieldDef::ContractType,'column' => Column::Left),
                    array('field_name'=> FieldDef::ContractId,'column' => Column::Left),
                    array('field_name'=> FieldDef::PIN,'column' => Column::Left),
                    array('field_name'=> FieldDef::CurrentContractAmount,'column' => Column::Left),
                    array('field_name'=> FieldDef::EndDate,'column' => Column::Left),
                    array('field_name'=> FieldDef::RegistrationDate,'column' => Column::Left),
                    array('field_name'=> FieldDef::Category,'column' => Column::Right),
                    array('field_name'=> FieldDef::Purpose,'column' => Column::Right),
                    array('field_name'=> FieldDef::Agency,'column' => Column::Right),
                    array('field_name'=> FieldDef::AptPIN,'column' => Column::Right),
                    array('field_name'=> FieldDef::AwardMethod,'column' => Column::Right),
                    array('field_name'=> FieldDef::StartDate,'column' => Column::Right),
                    array('field_name'=> FieldDef::ReceivedDate,'column' => Column::Right),
                    array('field_name'=> FieldDef::Year,'column' => Column::Right),
                    array('field_name'=> FieldDef::ContractSubmit,'column' => Column::None),
                ),
                DataSource::OtherGovernmentEntities => array(
                    array('field_name'=> FieldDef::Status,'column' => Column::Left),
                    array('field_name'=> FieldDef::Vendor,'column' => Column::Left),
                    array('field_name'=> FieldDef::ContractType,'column' => Column::Left),
                    array('field_name'=> FieldDef::ContractId,'column' => Column::Left),
                    array('field_name'=> FieldDef::EntityContractNumber,'column' => Column::Left),
                    array('field_name'=> FieldDef::CommodityLine,'column' => Column::Left),
                    array('field_name'=> FieldDef::BudgetName,'column' => Column::Left),
                    array('field_name'=> FieldDef::CurrentContractAmount,'column' => Column::Left),
                    array('field_name'=> FieldDef::RegistrationDate,'column' => Column::Left),
                    array('field_name'=> FieldDef::OtherGovernmentEntities,'column' => Column::Right),
                    array('field_name'=> FieldDef::Category,'column' => Column::Right),
                    array('field_name'=> FieldDef::Purpose,'column' => Column::Right),
                    array('field_name'=> FieldDef::PIN,'column' => Column::Right),
                    array('field_name'=> FieldDef::AptPIN,'column' => Column::Right),
                    array('field_name'=> FieldDef::AwardMethod,'column' => Column::Right),
                    array('field_name'=> FieldDef::StartDate,'column' => Column::Right),
                    array('field_name'=> FieldDef::EndDate,'column' => Column::Right),
                    array('field_name'=> FieldDef::Year,'column' => Column::Right),
                    array('field_name'=> FieldDef::ContractSubmit,'column' => Column::None),
                )
            );
            break;
    }
    return $fields;
}

function _checkbook_advanced_search_get_form($form, $domain, $agencies, $agency_attributes, $year_range)
{
    $field_configurations = _get_form_field_configurations($domain);

    $checkbook_form = new Form($domain);

    foreach ($field_configurations as $key => $value) {
        $data_source = $key;
        $field_configs = $value;
        $all_field_def = _get_all_field_definitions($domain,$data_source,$agencies,$agency_attributes,$year_range);

        $checkbook_content = new Content($data_source);

        foreach ($field_configs as $field_config){

            $field_name = $field_config['field_name'];
            $column = $field_config['column'];
            $field_def = $all_field_def[$field_name];
            $disabled = $field_def['disabled'];
            if((is_null($disabled)))
                $disabled = FALSE;
            $field = new Field($field_def['field_name'],$field_def['field_type'],$field_def['attributes'],$disabled);


            $checkbook_content->add_field($field,$column);
        }

        $checkbook_form->add_content($checkbook_content);
    }

    $form = $checkbook_form->generate_form($form);
    return $form;
}

/*
* This block is designed to print the advanced search form which is then exposed to the users using a jQuery modal dialog box
*/

/**
 * Implements hook_block_info().
 */
function checkbook_advanced_search_block_info()
{
    $blocks['checkbook_advanced_search_form'] = array(
        'info' => t('Checkbook Advanced Search Form Block'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    return $blocks;
}


/**
 * Implements hook_block_view().
 */
function checkbook_advanced_search_block_view($delta = '')
{
    switch ($delta) {
        case 'checkbook_advanced_search_form':
            $block['content'] = drupal_get_form('checkbook_advanced_search_form');
            break;
    }
    return $block;
}
