<?php
/**
 * This file is part of the Checkbook NYC financial transparency software.
 *
 * Copyright (c) 2012 – 2023 New York City
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use Drupal\checkbook_solr\Guru\CheckbookGuruOptionsAttributes;
use Drupal\checkbook_solr\Guru\CheckbookGuruOptionsLabels;


/**
 * @param string $data_source
 * @param string $domain
 * @param string $facet
 * @param array $filters
 * @return array
 */
function checkbook_solr_options_labels(string $data_source, string $domain, string $facet, array $filters=[])
{
  $Guru = new CheckbookGuruOptionsLabels($data_source);
  return $Guru->get_options($domain, $facet, $filters);
}
/**
 * @param string $data_source
 * @param string $domain
 * @param string $facet
 * @param array $filters
 * @return array
 */
function checkbook_solr_options_attributes(string $data_source, string $domain, string $facet, array $filters=[])
{
  $Guru = new CheckbookGuruOptionsAttributes($data_source);
  return $Guru->get_options($domain, $facet, $filters);
}
