<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
*
* Copyright (C) 2012, 2013 New York City
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



/**
 * Hook to load custom project specific utility functions during bootstrap..
 */
function checkbook_export_init(){
    require_once(drupal_get_path("module","checkbook_export") . "/includes/checkbook_export.inc");
}

/**
 * Implementation of hook_menu
 */
function checkbook_export_menu(){
    $items['export/transactions/form'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_export_form',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['export/transactions'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_export_transactions',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['export/grid/transactions/%'] = array(
        'title' => 'Checkbook Export',
        'page callback' => '_checkbook_export_grid_transactions',
        'page arguments' => array(3),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function checkbook_export_theme($existing, $type, $theme, $path){
    return array(
        'checkbook_export_default_theme' => array(
            'template' => 'checkbook_export',
            'arguments' => array('maxPages' => NULL,
                                'totalRecords' => NULL,
                                'displayRecords' => NULL
            )
        )
    );
}

/**
 * Implements hook_cron()
 */
function checkbook_export_cron()
{
    date_default_timezone_set('America/New_York');
    $variable_name = 'checkbook_export_cron_last_run';

    $now = time();

    if (variable_get($variable_name) > ($now - 3600)) { // skip if already ran within last hour
      return false;
    }

    LogHelper::log_notice("Running checkbook_export_cron");
    _checkbook_project_clean_files();
    variable_set($variable_name, $now);
}
