<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/


function data_controller_log_dc_log_message_listener() {
    $items[] = array(
        'classname' => 'ExceptionLogMessageFormatter',
        'priority' => -100);
    $items[] = array(
        'classname' => 'ArrayLogMessageSlicer',
        'priority' => -70);
    $items[] = array(
        'classname' => 'TextLogMessageTrimmer',
        'priority' => -50);
    $items[] = array(
        'classname' => 'PreservedTextLogMessageListener',
        'priority' => -30);

    return $items;
}
