<?php
/**
*	GNU AFFERO GENERAL PUBLIC LICENSE 
*	   Version 3, 19 November 2007
* This software is licensed under the GNU AGPL Version 3
* 	(see the file LICENSE for details)
*/



/**
 * Implements hook_menu()
 *
 * @return array
 */

function checkbook_autocomplete_menu() {
  $items = array();
  // Budget autocomplete paths
  $items['autocomplete/budget/department'] = array(
    'page callback' => '_checkbook_autocomplete_budget_department',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/budget/expcategory'] = array(
    'page callback' => '_checkbook_autocomplete_budget_expcategory',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/budget/budgetcode'] = array(
    'page callback' => '_checkbook_autocomplete_budget_budgetcode',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/budget/fundingsrc'] = array(
    'page callback' => '_checkbook_autocomplete_budget_fundingsrc',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/budget/revcat'] = array(
    'page callback' => '_checkbook_autocomplete_budget_revcat',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/budget/revsrc'] = array(
    'page callback'=>'_checkbook_autocomplete_budget_revsrc',
    'access callback'=>TRUE,
    'file'=>'/includes/checkbook_autocomplete_functions.inc',
    'type'=>MENU_CALLBACK
  );
  //Contracts Autocomplete Paths
  $items['autocomplete/contracts/vendor'] = array(
    'page callback' => '_checkbook_autocomplete_contracts_vendor',
    'access callback'=>TRUE,
    'file'=>'/includes/checkbook_autocomplete_functions.inc',
    'type'=>MENU_CALLBACK
  );
  $items['autocomplete/contracts/contract_number'] = array(
    'page callback' => '_checkbook_autocomplete_contracts_contract_number',
    'access callback'=>TRUE,
    'file'=>'/includes/checkbook_autocomplete_functions.inc',
    'type'=>MENU_CALLBACK
  );
  $items['autocomplete/contracts/apt_pin'] = array(
    'page callback' => '_checkbook_autocomplete_contracts_apt_pin',
    'access callback'=>TRUE,
    'file'=>'/includes/checkbook_autocomplete_functions.inc',
    'type'=>MENU_CALLBACK
  );
  $items['autocomplete/contracts/pin'] = array(
    'page callback' => '_checkbook_autocomplete_contracts_pin',
    'access callback'=>TRUE,
    'file'=>'/includes/checkbook_autocomplete_functions.inc',
    'type'=>MENU_CALLBACK
  );
  //Spending autocomplete paths
  $items['autocomplete/spending/payee'] = array(
    'page callback' => '_checkbook_autocomplete_spending_payee',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/spending/contractno'] = array(
    'page callback' => '_checkbook_autocomplete_spending_contractno',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/spending/capitalproject'] = array(
    'page callback' => '_checkbook_autocomplete_spending_capitalproject',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/spending/documentid'] = array(
    'page callback' => '_checkbook_autocomplete_spending_documentid',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );

  //Payroll autocomplete paths
  $items['autocomplete/payroll/title'] = array(
    'page callback' => '_checkbook_autocomplete_payroll_employee_name',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  //Revenue autocomplete paths
  $items['autocomplete/revenue/revenueclass'] = array(
    'page callback' => '_checkbook_autocomplete_revenue_revenueclass',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/revenue/revenuesource'] = array(
    'page callback' => '_checkbook_autocomplete_revenue_revenuesource',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/payroll/employee-name'] = array(
    'page callback' => '_checkbook_autocomplete_payroll_employee_name',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  $items['autocomplete/payroll/department'] = array(
    'page callback' => '_checkbook_autocomplete_payroll_department',
    'access callback' => TRUE,
    'file' => '/includes/checkbook_autocomplete_functions.inc',
    'type' => MENU_CALLBACK
  );
  return $items;
}
