<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
*
* Copyright (C) 2012, 2013 New York City
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/*************************************************************************************/
/* Widget Hooks                                                                      */
/*************************************************************************************/

function widget_highcharts_widget_metadata() {
	return array(
    'highcharts' => array(
      'name' => t('Highcharts'),
      'module' => 'widget_highcharts',
      'description' => t("This widget type implements highcharts.")
	)
	);
}

function widget_highcharts_widget_validate(&$node) {
	if (!isset($node->widgetConfig->chartConfig)) {
		form_set_error('body', "Property 'chartConfig' is required for widget type highchart.");
	}

}

function widget_highcharts_add_datatable_js($node){
    $id  = widget_unique_identifier($node);
    $js = "
		    var oTable" . $id  .  ";
		    jQuery(document).ready(function() {
		        oTable" . $id  .  " = jQuery('#table_" . widget_unique_identifier($node) . "').dataTable(
		        " . $node->widgetConfig->gridConfig->dataTableOptions . "
		        );
        } );"
    ;
    echo "<script type='text/javascript'>" . $js . "</script>";
}

function widget_highcharts_widget_view(&$node) {

	switch ($node->widgetConfig->widgetSubType){
		case "highstock":
			drupal_add_js(drupal_get_path('module', 'widget_highcharts') .'/highstock/9.3.2/code/highstock.src.js',array('group'=>JS_LIBRARY,'weight'=>-1));
			drupal_add_js(drupal_get_path('module', 'widget_highcharts') .'/highcharts-globals.js',array('group'=>JS_LIBRARY,'weight'=>0));
			return theme('widget_highstocks_default_theme', array('node' => $node));
		break;
		default :
      if(isset($node->widgetConfig->displayType) && $node->widgetConfig->displayType == 'gridview'){
          return theme($node->widgetConfig->gridConfig->template, array('node'=> $node));
      }else{
          _widget_highcharts_include_plugin();
          drupal_add_js(drupal_get_path('module', 'widget_highcharts') .'/highcharts-globals.js',array('group'=>JS_LIBRARY,'weight'=>0));
          return theme('widget_highcharts_default_theme', array('node' => $node));
      }
		break;
	}
}

function _widget_highcharts_include_plugin(){
	drupal_add_js(drupal_get_path('module', 'widget_highcharts') .'/highcharts/9.3.2/code/highcharts.src.js',array('group'=>JS_LIBRARY,'weight'=>-1));
}

function widget_highcharts_add_js_setting($node){
  $id = widget_unique_identifier($node);
  if ($node->widgetConfig->widgetSubType == 'highstock'){
    $type = 'highstock';
  } else {
    $type = 'highchart';
  }
  $chartConfig = widget_mergeJSFunctions($node, $node->widgetConfig->chartConfig);
  $options = array();
  $options['deferredRender'][]=array(
    'type'=>$type,
    'id'=>$id,
    'chartConfig'=>$chartConfig,
    'callback'=>$node->widgetConfig->callback
  );
  drupal_add_js($options, 'setting');
}

/*************************************************************************************/
/* Theme Hooks                                                                       */
/*************************************************************************************/

function widget_highcharts_theme($existing, $type, $theme, $path) {
	return array(
    'widget_highcharts_default_theme' => array(
	  'template' => 'highcharts',
      'arguments' => array('node' => NULL),
	),
	'widget_highstocks_default_theme' => array(
	  'template' => 'highstocks',
      'arguments' => array('node' => NULL),
	)
	);
}
