<?php
/**
* This file is part of the Checkbook NYC financial transparency software.
* 
* Copyright (C) 2012, 2013 New York City
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


function views_highcharts_init() {
		drupal_add_js(drupal_get_path('module', 'views_highcharts') .'/highcharts/2.1.1/js/highcharts.js');
		drupal_add_js(drupal_get_path('module', 'views_highcharts') .'/highcharts/2.1.1/js/modules/exporting.js');
		drupal_add_js(drupal_get_path('module', 'views_highcharts') .'/highcharts/highstock-globals.js');
}
/**
 * Implementation of hook_views_api().
 */
function views_highcharts_views_api() {
	return array('api' => 3);
}

/**
 * Implementation of hook_views_plugin().
 */
function views_highcharts_views_plugins() {
	$path = drupal_get_path('module', 'views_highcharts');
	return array(
    'module'  => 'views_highcharts',
      'style'   => array(                 // Declare the views_highcharts style plugin.
        'views_highcharts'      => array(
        'title'         => ('HighCharts'),
	    'path'          => $path,
	    'help'          => ('Displays views as HighCharts'), 
        'handler'         => 'views_plugin_style_highcharts',
		'theme'           => 'views_views_highcharts_style',
	    'theme file'      => 'views_views_highcharts_style.theme.inc',
	    'theme path'      => $path.'/theme',
        'uses row plugin' => FALSE,
        'uses fields'     => TRUE,
        'uses options'    => TRUE,
        'type'            => 'normal',
	    'even empty'      => FALSE
	  ),
	),
  );
}




